Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2019-06, with the labels that each got.

#656 fix off by one index problem
  simulation/g4simulation/g4intt/PHG4InttHitReco.cc
  simulation/g4simulation/g4intt/PHG4InttHitReco.h
Labels: CI-build-new-PENDING, CI-build-root5-PENDING, CI-cpp-check-PENDING

#657 Buffer Size and Split Level now feature of PHIODataNode
  offline/framework/phool/PHIODataNode.h
  offline/framework/phool/PHNodeIOManager.cc
  offline/framework/phool/PHNodeIOManager.h
  offline/framework/phool/PHObject.h
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#658 Fixing `PHG4SpacalPrototypeSteppingAction`
  simulation/g4simulation/g4detectors/PHG4SpacalPrototypeSteppingAction.cc
  simulation/g4simulation/g4main/PHG4Reco.cc
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#659 Count and print EMCal block density
  simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#663 Fix cppcheck
  generators/hijing/Makefile.am
  generators/hijing/src/hijfst.cc
  generators/sHijing/configure.ac
  offline/packages/HelixHough/Seamstress/Needle.h
  simulation/g4simulation/g4detectors/PHG4BlockDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4Cell.cc
  simulation/g4simulation/g4detectors/PHG4Cell.h
  simulation/g4simulation/g4detectors/PHG4CylinderCell.h
  simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4HcalPrototypeDetector.cc
  simulation/g4simulation/g4detectors/PHG4HcalPrototypeDetector.h
  simulation/g4simulation/g4detectors/PHG4OuterHcalFieldSetup.cc
  simulation/g4simulation/g4detectors/PHG4mRICHDetector.cc
  simulation/g4simulation/g4detectors/PHG4mRICHDetector.h
  simulation/g4simulation/g4hough/PHG4InitZVertexing.h
  simulation/g4simulation/g4hough/PHG4KalmanPatRec.cc
  simulation/g4simulation/g4hough/PHG4PatternReco.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-FAIL, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-FAIL

#664 Revert "Merge pull request #660 from bogui56/master"
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHHoughSeeding.cc
  offline/packages/trackreco/PHHoughSeeding.h
  offline/packages/trackreco/PHTrackFitting.cc
  offline/packages/trackreco/PHTrackFitting.h
  offline/packages/trackreco/PHTrackPropagating.cc
  offline/packages/trackreco/PHTrackPropagating.h
  offline/packages/trackreco/PHTrackSeeding.cc
  offline/packages/trackreco/PHTrackSeeding.h
  offline/packages/trackreco/PHTrackSetMerging.cc
  offline/packages/trackreco/PHTrackSetMerging.h
  offline/packages/trackreco/PHTrackSetMergingLinkDef.h
  offline/packages/trackreco/PHTruthTrackSeeding.cc
  offline/packages/trackreco/PHTruthTrackSeeding.h
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4eval/SvtxTrackEval.cc
Labels: CI-DST-readback-PENDING, CI-build-clang-PENDING, CI-build-new-PENDING, CI-build-root5-PENDING, CI-calo-QA-PENDING, CI-cpp-check-PENDING, CI-valgrind-PENDING

#665 Track projection move
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHGenFitTrackProjection.cc
  offline/packages/trackreco/PHGenFitTrackProjection.h
  offline/packages/trackreco/PHGenFitTrackProjectionLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#666 remove g4hough remnants
  offline/QA/modules/Makefile.am
  offline/QA/modules/QAG4SimulationCalorimeterSum.cc
  offline/packages/NodeDump/Makefile.am
  simulation/g4simulation/g4dst/Makefile.am
  simulation/g4simulation/g4histos/Makefile.am
  simulation/g4simulation/g4jets/Makefile.am
  simulation/g4simulation/g4vertex/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-FAIL, CI-build-root5-FAIL, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-FAIL

#669 Tweak fun4all
  offline/framework/fun4all/Fun4AllDummyInputManager.cc
  offline/framework/fun4all/Fun4AllDummyInputManager.h
  offline/framework/fun4all/Fun4AllEventOutStream.h
  offline/framework/fun4all/Fun4AllPrdfInputManager.cc
  offline/framework/fun4all/Fun4AllPrdfInputManager.h
  offline/framework/fun4all/Fun4AllSyncManager.cc
  offline/framework/fun4all/Fun4AllSyncManager.h
  simulation/g4simulation/g4dst/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
