Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2019-01, with the labels that each got.

#509 TPC with a rigid central membrane
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4tpc/PHG4TPCDefs.h
  simulation/g4simulation/g4tpc/PHG4TPCDetector.cc
  simulation/g4simulation/g4tpc/PHG4TPCSubsystem.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-release, CI-valgrind-AVAILABLE, test and suggestion welcomed

#540 Clusterizer
  offline/packages/CaloReco/BEmcRecFEMC.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#542 Hcal proto4
  offline/packages/Prototype4/PROTOTYPE4_FEM.C
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#541 Fix PHObject
  offline/framework/phool/PHObject.cc
  offline/framework/phool/PHObject.h
  offline/packages/PHGeometry/PHGeomIOTGeo.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#546 Root6 g4detectors
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4Cell.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h
  simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.h
  simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h
  simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4ForwardHcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4HcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4HcalPrototypeDetector.cc
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#547 create dictionaries only for root5
  offline/database/PHParameter/Makefile.am
  offline/database/PHParameter/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#548 Root6 phpythia6
  generators/PHPythia6/Makefile.am
  generators/PHPythia6/PHPy6ForwardElectronTrig.C
  generators/PHPythia6/PHPy6ForwardElectronTrig.cc
  generators/PHPythia6/PHPy6ForwardElectronTrig.h
  generators/PHPythia6/PHPy6ForwardElectronTrigLinkDef.h
  generators/PHPythia6/PHPy6GenTrigger.cc
  generators/PHPythia6/PHPy6GenTrigger.h
  generators/PHPythia6/PHPy6GenTriggerLinkDef.h
  generators/PHPythia6/PHPy6JetTrigger.C
  generators/PHPythia6/PHPy6JetTrigger.cc
  generators/PHPythia6/PHPy6JetTrigger.h
  generators/PHPythia6/PHPy6JetTriggerLinkDef.h
  generators/PHPythia6/PHPy6ParticleTrigger.cc
  generators/PHPythia6/PHPy6ParticleTrigger.h
  generators/PHPythia6/PHPy6ParticleTriggerLinkDef.h
  generators/PHPythia6/PHPythia6.C
  generators/PHPythia6/PHPythia6.cc
  generators/PHPythia6/PHPythia6.h
  generators/PHPythia6/PHPythia6LinkDef.h
  generators/PHPythia6/configure.ac
  simulation/g4simulation/g4detectors/PHG4HcalPrototypeDetector.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#549 Root6 phpythia8
  generators/PHPythia8/Makefile.am
  generators/PHPythia8/PHPy8GenTrigger.cc
  generators/PHPythia8/PHPy8GenTrigger.h
  generators/PHPythia8/PHPy8GenTriggerLinkDef.h
  generators/PHPythia8/PHPy8JetTrigger.C
  generators/PHPythia8/PHPy8JetTrigger.cc
  generators/PHPythia8/PHPy8JetTrigger.h
  generators/PHPythia8/PHPy8JetTriggerLinkDef.h
  generators/PHPythia8/PHPy8ParticleTrigger.C
  generators/PHPythia8/PHPy8ParticleTrigger.cc
  generators/PHPythia8/PHPy8ParticleTrigger.h
  generators/PHPythia8/PHPy8ParticleTriggerLinkDef.h
  generators/PHPythia8/PHPythia8.cc
  generators/PHPythia8/PHPythia8.h
  generators/PHPythia8/PHPythia8LinkDef.h
  generators/PHPythia8/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#550 Root6 phsartre
  generators/PHSartre/Makefile.am
  generators/PHSartre/PHSartre.C
  generators/PHSartre/PHSartre.cc
  generators/PHSartre/PHSartre.h
  generators/PHSartre/PHSartreGenTrigger.cc
  generators/PHSartre/PHSartreGenTrigger.h
  generators/PHSartre/PHSartreGenTriggerLinkDef.h
  generators/PHSartre/PHSartreLinkDef.h
  generators/PHSartre/PHSartreParticleTrigger.C
  generators/PHSartre/PHSartreParticleTrigger.cc
  generators/PHSartre/PHSartreParticleTrigger.h
  generators/PHSartre/PHSartreParticleTriggerLinkDef.h
  generators/PHSartre/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#552 Root6 phhepmc
  generators/phhepmc/Fun4AllHepMCInputManager.cc
  generators/phhepmc/Fun4AllHepMCInputManager.h
  generators/phhepmc/Fun4AllHepMCInputManagerLinkDef.h
  generators/phhepmc/Fun4AllHepMCOutputManager.cc
  generators/phhepmc/Fun4AllHepMCOutputManager.h
  generators/phhepmc/Fun4AllHepMCOutputManagerLinkDef.h
  generators/phhepmc/Fun4AllHepMCPileupInputManager.cc
  generators/phhepmc/Fun4AllHepMCPileupInputManager.h
  generators/phhepmc/Fun4AllHepMCPileupInputManagerLinkDef.h
  generators/phhepmc/Fun4AllOscarInputManager.cc
  generators/phhepmc/Fun4AllOscarInputManager.h
  generators/phhepmc/Fun4AllOscarInputManagerLinkDef.h
  generators/phhepmc/HepMCFlowAfterBurner.cc
  generators/phhepmc/HepMCFlowAfterBurnerLinkDef.h
  generators/phhepmc/Makefile.am
  generators/phhepmc/PHGenEvent.cc
  generators/phhepmc/PHGenEvent.h
  generators/phhepmc/PHGenEventLinkDef.h
  generators/phhepmc/PHGenEventList.cc
  generators/phhepmc/PHGenEventList.h
  generators/phhepmc/PHGenEventListLinkDef.h
  generators/phhepmc/PHGenEventListV1LinkDef.h
  generators/phhepmc/PHGenEventListv1.cc
  generators/phhepmc/PHGenEventListv1.h
  generators/phhepmc/PHGenEventListv1LinkDef.h
  generators/phhepmc/PHGenEventV1LinkDef.h
  generators/phhepmc/PHGenEventv1.cc
  generators/phhepmc/PHGenEventv1.h
  generators/phhepmc/PHGenEventv1LinkDef.h
  generators/phhepmc/PHGenIntegral.h
  generators/phhepmc/PHGenIntegralLinkDef.h
  generators/phhepmc/PHGenIntegralv1.cc
  generators/phhepmc/PHGenIntegralv1.h
  generators/phhepmc/PHGenIntegralv1LinkDef.h
  generators/phhepmc/PHHepMCGenEvent.cc
  generators/phhepmc/PHHepMCGenEvent.h
  generators/phhepmc/PHHepMCGenEventLinkDef.h
  generators/phhepmc/PHHepMCGenEventMap.cc
  generators/phhepmc/PHHepMCGenEventMap.h
  generators/phhepmc/PHHepMCGenEventMapLinkDef.h
  generators/phhepmc/PHHepMCGenHelper.cc
  generators/phhepmc/PHHepMCGenHelper.h
  generators/phhepmc/PHHepMCGenHelperLinkDef.h
  generators/phhepmc/PHHepMCLinkDef.h
  generators/phhepmc/PHHepMCParticleSelectorDecayProductChain.cc
  generators/phhepmc/PHHepMCParticleSelectorDecayProductChain.h
  generators/phhepmc/PHHepMCParticleSelectorDecayProductChainLinkDef.h
  generators/phhepmc/PHHepMC_ioLinkDef.h
  generators/phhepmc/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#555 Root6 g4calo
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
  simulation/g4simulation/g4calo/HcalRawTowerBuilderLinkDef.h
  simulation/g4simulation/g4calo/Makefile.am
  simulation/g4simulation/g4calo/Prototype2RawTowerBuilder.cc
  simulation/g4simulation/g4calo/Prototype2RawTowerBuilder.h
  simulation/g4simulation/g4calo/Prototype2RawTowerBuilderLinkDef.h
  simulation/g4simulation/g4calo/RawTowerBuilder.h
  simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.cc
  simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.h
  simulation/g4simulation/g4calo/RawTowerBuilderByHitIndexLinkDef.h
  simulation/g4simulation/g4calo/RawTowerBuilderLinkDef.h
  simulation/g4simulation/g4calo/RawTowerDigitizer.cc
  simulation/g4simulation/g4calo/RawTowerDigitizer.h
  simulation/g4simulation/g4calo/RawTowerDigitizerLinkDef.h
  simulation/g4simulation/g4calo/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#557 Root6 g4histos
  simulation/g4simulation/g4histos/G4AnalysisLinkDef.h
  simulation/g4simulation/g4histos/G4CellNtuple.cc
  simulation/g4simulation/g4histos/G4CellNtuple.h
  simulation/g4simulation/g4histos/G4CellNtupleLinkDef.h
  simulation/g4simulation/g4histos/G4EdepNtuple.cc
  simulation/g4simulation/g4histos/G4EdepNtuple.h
  simulation/g4simulation/g4histos/G4EdepNtupleLinkDef.h
  simulation/g4simulation/g4histos/G4EvtTree.h
  simulation/g4simulation/g4histos/G4HitNtuple.cc
  simulation/g4simulation/g4histos/G4HitNtuple.h
  simulation/g4simulation/g4histos/G4HitNtupleLinkDef.h
  simulation/g4simulation/g4histos/G4HitTTree.cc
  simulation/g4simulation/g4histos/G4HitTTree.h
  simulation/g4simulation/g4histos/G4HitTTreeLinkDef.h
  simulation/g4simulation/g4histos/G4RawTowerTTree.cc
  simulation/g4simulation/g4histos/G4RawTowerTTree.h
  simulation/g4simulation/g4histos/G4RawTowerTTreeLinkDef.h
  simulation/g4simulation/g4histos/G4RootHitContainer.cc
  simulation/g4simulation/g4histos/G4RootHitContainer.h
  simulation/g4simulation/g4histos/G4RootHitContainerLinkDef.h
  simulation/g4simulation/g4histos/G4RootRawTower.cc
  simulation/g4simulation/g4histos/G4RootRawTower.h
  simulation/g4simulation/g4histos/G4RootRawTowerContainer.cc
  simulation/g4simulation/g4histos/G4RootRawTowerContainer.h
  simulation/g4simulation/g4histos/G4RootRawTowerContainerLinkDef.h
  simulation/g4simulation/g4histos/G4RootRawTowerLinkDef.h
  simulation/g4simulation/g4histos/G4RootScintillatorSlat.cc
  simulation/g4simulation/g4histos/G4RootScintillatorSlat.h
  simulation/g4simulation/g4histos/G4RootScintillatorSlatContainer.cc
  simulation/g4simulation/g4histos/G4RootScintillatorSlatContainer.h
  simulation/g4simulation/g4histos/G4RootScintillatorSlatContainerLinkDef.h
  simulation/g4simulation/g4histos/G4RootScintillatorSlatLinkDef.h
  simulation/g4simulation/g4histos/G4RootScintillatorTower.h
  simulation/g4simulation/g4histos/G4RootScintillatorTowerContainer.cc
  simulation/g4simulation/g4histos/G4RootScintillatorTowerContainer.h
  simulation/g4simulation/g4histos/G4RootScintillatorTowerContainerLinkDef.h
  simulation/g4simulation/g4histos/G4RootScintillatorTowerLinkDef.h
  simulation/g4simulation/g4histos/G4ScintillatorSlatTTree.cc
  simulation/g4simulation/g4histos/G4ScintillatorSlatTTree.h
  simulation/g4simulation/g4histos/G4ScintillatorSlatTTreeLinkDef.h
  simulation/g4simulation/g4histos/G4ScintillatorTowerTTree.cc
  simulation/g4simulation/g4histos/G4ScintillatorTowerTTree.h
  simulation/g4simulation/g4histos/G4ScintillatorTowerTTreeLinkDef.h
  simulation/g4simulation/g4histos/G4SnglNtuple.cc
  simulation/g4simulation/g4histos/G4SnglNtuple.h
  simulation/g4simulation/g4histos/G4SnglNtupleLinkDef.h
  simulation/g4simulation/g4histos/G4SnglTree.cc
  simulation/g4simulation/g4histos/G4SnglTree.h
  simulation/g4simulation/g4histos/G4SnglTreeLinkDef.h
  simulation/g4simulation/g4histos/G4TowerNtuple.cc
  simulation/g4simulation/g4histos/G4TowerNtuple.h
  simulation/g4simulation/g4histos/G4TowerNtupleLinkDef.h
  simulation/g4simulation/g4histos/Makefile.am
  simulation/g4simulation/g4histos/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#564 Root6 qa modules
  offline/QA/modules/Makefile.am
  offline/QA/modules/QAG4SimulationCalorimeter.C
  offline/QA/modules/QAG4SimulationCalorimeter.cc
  offline/QA/modules/QAG4SimulationCalorimeter.h
  offline/QA/modules/QAG4SimulationCalorimeterLinkDef.h
  offline/QA/modules/QAG4SimulationCalorimeterSum.C
  offline/QA/modules/QAG4SimulationCalorimeterSum.cc
  offline/QA/modules/QAG4SimulationCalorimeterSum.h
  offline/QA/modules/QAG4SimulationCalorimeterSumLinkDef.h
  offline/QA/modules/QAG4SimulationJet.C
  offline/QA/modules/QAG4SimulationJet.cc
  offline/QA/modules/QAG4SimulationJet.h
  offline/QA/modules/QAG4SimulationJetLinkDef.h
  offline/QA/modules/QAHistManagerDef.C
  offline/QA/modules/QAHistManagerDef.cc
  offline/QA/modules/QAHistManagerDef.h
  offline/QA/modules/QAHistManagerDefLinkDef.h
  offline/QA/modules/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#565 Root6 frog
  offline/framework/frog/FROG.h
  offline/framework/frog/FROGLinkDef.h
  offline/framework/frog/Makefile.am
  offline/framework/frog/configure.ac
  offline/framework/phool/Makefile.am
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE
