Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2019-02, with the labels that each got.

#566 Root6 calobase
  offline/packages/CaloBase/Makefile.am
  offline/packages/CaloBase/RawCluster.cc
  offline/packages/CaloBase/RawCluster.h
  offline/packages/CaloBase/RawClusterContainer.cc
  offline/packages/CaloBase/RawClusterContainer.h
  offline/packages/CaloBase/RawClusterContainerLinkDef.h
  offline/packages/CaloBase/RawClusterDefs.h
  offline/packages/CaloBase/RawClusterDefsLinkDef.h
  offline/packages/CaloBase/RawClusterLinkDef.h
  offline/packages/CaloBase/RawClusterUtility.cc
  offline/packages/CaloBase/RawClusterUtility.h
  offline/packages/CaloBase/RawClusterUtilityLinkDef.h
  offline/packages/CaloBase/RawClusterv1.cc
  offline/packages/CaloBase/RawClusterv1.h
  offline/packages/CaloBase/RawClusterv1LinkDef.h
  offline/packages/CaloBase/RawTower.h
  offline/packages/CaloBase/RawTowerContainer.cc
  offline/packages/CaloBase/RawTowerContainer.h
  offline/packages/CaloBase/RawTowerContainerLinkDef.h
  offline/packages/CaloBase/RawTowerDeadMap.cc
  offline/packages/CaloBase/RawTowerDeadMap.h
  offline/packages/CaloBase/RawTowerDeadMapLinkDef.h
  offline/packages/CaloBase/RawTowerDeadMapv1.cc
  offline/packages/CaloBase/RawTowerDeadMapv1.h
  offline/packages/CaloBase/RawTowerDeadMapv1LinkDef.h
  offline/packages/CaloBase/RawTowerDefs.h
  offline/packages/CaloBase/RawTowerDefsLinkDef.h
  offline/packages/CaloBase/RawTowerGeom.cc
  offline/packages/CaloBase/RawTowerGeom.h
  offline/packages/CaloBase/RawTowerGeomContainer.cc
  offline/packages/CaloBase/RawTowerGeomContainer.h
  offline/packages/CaloBase/RawTowerGeomContainerLinkDef.h
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.cc
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1LinkDef.h
  offline/packages/CaloBase/RawTowerGeomContainerv1.cc
  offline/packages/CaloBase/RawTowerGeomContainerv1.h
  offline/packages/CaloBase/RawTowerGeomContainerv1LinkDef.h
  offline/packages/CaloBase/RawTowerGeomLinkDef.h
  offline/packages/CaloBase/RawTowerGeomv1.cc
  offline/packages/CaloBase/RawTowerGeomv1.h
  offline/packages/CaloBase/RawTowerGeomv1LinkDef.h
  offline/packages/CaloBase/RawTowerGeomv2.cc
  offline/packages/CaloBase/RawTowerGeomv2.h
  offline/packages/CaloBase/RawTowerGeomv2LinkDef.h
  offline/packages/CaloBase/RawTowerGeomv3.cc
  offline/packages/CaloBase/RawTowerGeomv3.h
  offline/packages/CaloBase/RawTowerGeomv3LinkDef.h
  offline/packages/CaloBase/RawTowerLinkDef.h
  offline/packages/CaloBase/RawTowerv1.cc
  offline/packages/CaloBase/RawTowerv1.h
  offline/packages/CaloBase/RawTowerv1LinkDef.h
  offline/packages/CaloBase/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#567 Root6 caloreco
  offline/packages/CaloBase/RawTowerDefs.h
  offline/packages/CaloReco/BEmcCluster.cc
  offline/packages/CaloReco/BEmcCluster.h
  offline/packages/CaloReco/BEmcRec.cc
  offline/packages/CaloReco/BEmcRec.h
  offline/packages/CaloReco/BEmcRecCEMC.cc
  offline/packages/CaloReco/BEmcRecCEMC.h
  offline/packages/CaloReco/BEmcRecEEMC.cc
  offline/packages/CaloReco/BEmcRecEEMC.h
  offline/packages/CaloReco/BEmcRecFEMC.cc
  offline/packages/CaloReco/BEmcRecFEMC.h
  offline/packages/CaloReco/Makefile.am
  offline/packages/CaloReco/PHMakeGroups.h
  offline/packages/CaloReco/RawClusterBuilderFwd.cc
  offline/packages/CaloReco/RawClusterBuilderFwd.h
  offline/packages/CaloReco/RawClusterBuilderFwdLinkDef.h
  offline/packages/CaloReco/RawClusterBuilderGraph.cc
  offline/packages/CaloReco/RawClusterBuilderGraph.h
  offline/packages/CaloReco/RawClusterBuilderGraphLinkDef.h
  offline/packages/CaloReco/RawClusterBuilderTemplate.cc
  offline/packages/CaloReco/RawClusterBuilderTemplate.h
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.h
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMCLinkDef.h
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.h
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMCLinkDef.h
  offline/packages/CaloReco/RawClusterBuilderTemplateLinkDef.h
  offline/packages/CaloReco/RawClusterDeadAreaMask.cc
  offline/packages/CaloReco/RawClusterDeadAreaMask.h
  offline/packages/CaloReco/RawClusterDeadAreaMaskLinkDef.h
  offline/packages/CaloReco/RawClusterPositionCorrection.cc
  offline/packages/CaloReco/RawClusterPositionCorrection.h
  offline/packages/CaloReco/RawClusterPositionCorrectionLinkDef.h
  offline/packages/CaloReco/RawTowerCalibration.cc
  offline/packages/CaloReco/RawTowerCalibration.h
  offline/packages/CaloReco/RawTowerCalibrationLinkDef.h
  offline/packages/CaloReco/RawTowerCombiner.cc
  offline/packages/CaloReco/RawTowerCombiner.h
  offline/packages/CaloReco/RawTowerCombinerLinkDef.h
  offline/packages/CaloReco/RawTowerDeadMapLoader.cc
  offline/packages/CaloReco/RawTowerDeadMapLoader.h
  offline/packages/CaloReco/RawTowerDeadMapLoaderLinkDef.h
  offline/packages/CaloReco/RawTowerDeadTowerInterp.cc
  offline/packages/CaloReco/RawTowerDeadTowerInterp.h
  offline/packages/CaloReco/RawTowerDeadTowerInterpLinkDef.h
  offline/packages/CaloReco/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#568 Root6 clusteriso
  offline/packages/ClusterIso/ClusterIso.cc
  offline/packages/ClusterIso/ClusterIso.h
  offline/packages/ClusterIso/ClusterIsoLinkDef.h
  offline/packages/ClusterIso/Makefile.am
  offline/packages/ClusterIso/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#571 Root6 phfield
  offline/packages/PHField/Makefile.am
  offline/packages/PHField/PHField.cc
  offline/packages/PHField/PHField.h
  offline/packages/PHField/PHField2D.cc
  offline/packages/PHField/PHField2D.h
  offline/packages/PHField/PHField3DCartesian.cc
  offline/packages/PHField/PHField3DCartesian.h
  offline/packages/PHField/PHField3DCylindrical.cc
  offline/packages/PHField/PHField3DCylindrical.h
  offline/packages/PHField/PHFieldConfig.h
  offline/packages/PHField/PHFieldConfigLinkDef.h
  offline/packages/PHField/PHFieldConfig_v1LinkDef.h
  offline/packages/PHField/PHFieldConfig_v2.cc
  offline/packages/PHField/PHFieldConfig_v2LinkDef.h
  offline/packages/PHField/PHFieldConfigv1.cc
  offline/packages/PHField/PHFieldConfigv1.h
  offline/packages/PHField/PHFieldConfigv1LinkDef.h
  offline/packages/PHField/PHFieldConfigv2.cc
  offline/packages/PHField/PHFieldConfigv2.h
  offline/packages/PHField/PHFieldConfigv2LinkDef.h
  offline/packages/PHField/PHFieldUniform.cc
  offline/packages/PHField/PHFieldUniform.h
  offline/packages/PHField/PHFieldUtility.cc
  offline/packages/PHField/PHFieldUtility.h
  offline/packages/PHField/PHFieldUtilityLinkDef.h
  offline/packages/PHField/configure.ac
  offline/packages/PHGenFitPkg/GenFitExp/Field.cc
  offline/packages/PHGenFitPkg/GenFitExp/Makefile.am
  simulation/g4simulation/g4main/PHG4Reco.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#572 Root6 phgeometry
  offline/packages/PHGeometry/Makefile.am
  offline/packages/PHGeometry/PHGeomFileImport.cc
  offline/packages/PHGeometry/PHGeomFileImport.h
  offline/packages/PHGeometry/PHGeomFileImportLinkDef.h
  offline/packages/PHGeometry/PHGeomIOTGeo.cc
  offline/packages/PHGeometry/PHGeomIOTGeo.h
  offline/packages/PHGeometry/PHGeomIOTGeoLinkDef.h
  offline/packages/PHGeometry/PHGeomTGeo.cc
  offline/packages/PHGeometry/PHGeomTGeo.h
  offline/packages/PHGeometry/PHGeomTGeoLinkDef.h
  offline/packages/PHGeometry/PHGeomUtility.cc
  offline/packages/PHGeometry/PHGeomUtility.h
  offline/packages/PHGeometry/PHGeomUtilityLinkDef.h
  offline/packages/PHGeometry/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#573 Root6 genfitexp
  offline/packages/PHGenFitPkg/GenFitExp/Field.cc
  offline/packages/PHGenFitPkg/GenFitExp/Field.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#574 Root6 phgenfit
  offline/packages/PHGenFitPkg/PHGenFit/Fitter.cc
  offline/packages/PHGenFitPkg/PHGenFit/Fitter.h
  offline/packages/PHGenFitPkg/PHGenFit/Makefile.am
  offline/packages/PHGenFitPkg/PHGenFit/Measurement.cc
  offline/packages/PHGenFitPkg/PHGenFit/Measurement.h
  offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.cc
  offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.h
  offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.cc
  offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.h
  offline/packages/PHGenFitPkg/PHGenFit/Tools.cc
  offline/packages/PHGenFitPkg/PHGenFit/Tools.h
  offline/packages/PHGenFitPkg/PHGenFit/Track.cc
  offline/packages/PHGenFitPkg/PHGenFit/Track.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#575 Root6 intt
  offline/packages/Prototype2/CaloCalibration.cc
  offline/packages/Prototype2/CaloUnpackPRDF.cc
  offline/packages/Prototype2/GenericUnpackPRDF.cc
  offline/packages/Prototype2/Makefile.am
  offline/packages/Prototype2/PROTOTYPE2_FEM.cc
  offline/packages/Prototype2/RunInfoUnpackPRDF.cc
  offline/packages/Prototype2/TempInfoUnpackPRDF.cc
  offline/packages/intt/Makefile.am
  offline/packages/intt/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#578 Root6 tpcdaq
  offline/packages/tpcdaq/Makefile.am
  offline/packages/tpcdaq/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#581 Root6 trackreco
  offline/packages/trackreco/AssocInfoContainer.cc
  offline/packages/trackreco/AssocInfoContainer.h
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PH3DVertexing.cc
  offline/packages/trackreco/PH3DVertexing.h
  offline/packages/trackreco/PHGenFitTrkFitter.cc
  offline/packages/trackreco/PHGenFitTrkFitter.h
  offline/packages/trackreco/PHGenFitTrkProp.cc
  offline/packages/trackreco/PHGenFitTrkProp.h
  offline/packages/trackreco/PHHoughAllInOne.cc
  offline/packages/trackreco/PHHoughAllInOne.h
  offline/packages/trackreco/PHHoughSeeding.cc
  offline/packages/trackreco/PHHoughSeeding.h
  offline/packages/trackreco/PHInitVertexing.cc
  offline/packages/trackreco/PHInitVertexing.h
  offline/packages/trackreco/PHRaveVertexing.cc
  offline/packages/trackreco/PHRaveVertexing.h
  offline/packages/trackreco/PHTrackFitting.cc
  offline/packages/trackreco/PHTrackFitting.h
  offline/packages/trackreco/PHTrackPropagating.cc
  offline/packages/trackreco/PHTrackPropagating.h
  offline/packages/trackreco/PHTrackSeeding.cc
  offline/packages/trackreco/PHTrackSeeding.h
  offline/packages/trackreco/PHTruthTrackSeeding.cc
  offline/packages/trackreco/PHTruthTrackSeeding.h
  offline/packages/trackreco/PHTruthVertexing.cc
  offline/packages/trackreco/PHTruthVertexing.h
  offline/packages/trackreco/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#582 Root6 trigger
  offline/packages/trigger/CaloTriggerInfoLinkDef.h
  offline/packages/trigger/CaloTriggerInfo_v1LinkDef.h
  offline/packages/trigger/CaloTriggerInfov1.cc
  offline/packages/trigger/CaloTriggerInfov1.h
  offline/packages/trigger/CaloTriggerInfov1LinkDef.h
  offline/packages/trigger/CaloTriggerSim.cc
  offline/packages/trigger/CaloTriggerSim.h
  offline/packages/trigger/CaloTriggerSimLinkDef.h
  offline/packages/trigger/Makefile.am
  offline/packages/trigger/configure.ac
  simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc
  simulation/g4simulation/g4detectors/PHG4HcalCellReco.h
Labels: CI-build-new-PASS, CI-build-root6-FAIL, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#583 Root6 jetbackground
  offline/packages/jetbackground/CopyAndSubtractJets.cc
  offline/packages/jetbackground/CopyAndSubtractJets.h
  offline/packages/jetbackground/CopyAndSubtractJetsLinkDef.h
  offline/packages/jetbackground/DetermineTowerBackground.cc
  offline/packages/jetbackground/DetermineTowerBackground.h
  offline/packages/jetbackground/DetermineTowerBackgroundLinkDef.h
  offline/packages/jetbackground/FastJetAlgoSub.cc
  offline/packages/jetbackground/FastJetAlgoSub.h
  offline/packages/jetbackground/FastJetAlgoSubLinkDef.h
  offline/packages/jetbackground/Makefile.am
  offline/packages/jetbackground/RetowerCEMC.cc
  offline/packages/jetbackground/RetowerCEMC.h
  offline/packages/jetbackground/RetowerCEMCLinkDef.h
  offline/packages/jetbackground/SubtractTowers.cc
  offline/packages/jetbackground/SubtractTowers.h
  offline/packages/jetbackground/SubtractTowersCS.cc
  offline/packages/jetbackground/SubtractTowersCS.h
  offline/packages/jetbackground/SubtractTowersCSLinkDef.h
  offline/packages/jetbackground/SubtractTowersLinkDef.h
  offline/packages/jetbackground/TowerBackground.h
  offline/packages/jetbackground/TowerBackgroundLinkDef.h
  offline/packages/jetbackground/TowerBackground_v1.C
  offline/packages/jetbackground/TowerBackground_v1.h
  offline/packages/jetbackground/TowerBackground_v1LinkDef.h
  offline/packages/jetbackground/TowerBackgroundv1.cc
  offline/packages/jetbackground/TowerBackgroundv1.h
  offline/packages/jetbackground/TowerBackgroundv1LinkDef.h
  offline/packages/jetbackground/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#584 Root6 vararray
  offline/packages/vararray/Makefile.am
  offline/packages/vararray/VariableArray.cc
  offline/packages/vararray/VariableArray.h
  offline/packages/vararray/VariableArrayContainer.cc
  offline/packages/vararray/VariableArrayContainer.h
  offline/packages/vararray/VariableArrayContainerLinkDef.h
  offline/packages/vararray/VariableArrayIds.h
  offline/packages/vararray/VariableArrayLinkDef.h
  offline/packages/vararray/VariableArrayUtils.cc
  offline/packages/vararray/VariableArrayUtils.h
  offline/packages/vararray/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#585 Remove classimp
  offline/packages/Prototype3/RawTower_Prototype3.cc
  offline/packages/Prototype3/RawTower_Temperature.cc
  offline/packages/Prototype4/RawTower_Prototype4.cc
  offline/packages/Prototype4/RawTower_Temperature.cc
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4EventHeader.cc
  simulation/g4simulation/g4main/PHG4EventHeaderv1.cc
  simulation/g4simulation/g4main/PHG4Hitv1.cc
  simulation/g4simulation/g4main/PHG4InEvent.cc
  simulation/g4simulation/g4main/PHG4Particle.cc
  simulation/g4simulation/g4main/PHG4Particlev1.cc
  simulation/g4simulation/g4main/PHG4Particlev2.cc
  simulation/g4simulation/g4main/PHG4Shower.cc
  simulation/g4simulation/g4main/PHG4Showerv1.cc
  simulation/g4simulation/g4main/PHG4VtxPoint.cc
  simulation/g4simulation/g4main/PHG4VtxPointv1.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#586 oops, 2 dictionaries made it into the source list
  simulation/g4simulation/g4detectors/Makefile.am
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#587 fix forgotten dictionaries
  simulation/g4simulation/g4hough/Makefile.am
  simulation/g4simulation/g4intt/Makefile.am
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#589 Tktdrk intt sim
  offline/database/PHParameter/PHParameters.cc
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.cc
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#580 Added noise electron when determining ADC value.
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.cc
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.h
Labels: CI-build-new-FAIL, CI-build-root6-FAIL, CI-calo-QA-FAIL, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#590 need to install Prototype2RawTowerBuilder.h
  simulation/g4simulation/g4calo/Makefile.am
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-PASS, CI-valgrind-AVAILABLE

#592 Intt geom
  simulation/g4simulation/g4intt/PHG4INTTDetector.cc
  simulation/g4simulation/g4intt/PHG4INTTDetector.h
  simulation/g4simulation/g4intt/PHG4INTTSubsystem.cc
  simulation/g4simulation/g4main/PHG4Reco.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#591 Updated E864 fEMC tower geometry
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#593 enable multiple prdf input managers
  offline/framework/fun4all/Fun4AllPrdfInputManager.cc
  offline/framework/fun4all/Fun4AllPrdfInputManager.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#594 Eic physics list
  simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.cc
  simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.hh
  simulation/g4simulation/EICPhysicsList/EICPhysicsList.cc
  simulation/g4simulation/EICPhysicsList/EICPhysicsList.hh
  simulation/g4simulation/EICPhysicsList/GammaLeptoNuclearPhysics.cc
  simulation/g4simulation/EICPhysicsList/GammaLeptoNuclearPhysics.hh
  simulation/g4simulation/EICPhysicsList/HyperonPhysics.cc
  simulation/g4simulation/EICPhysicsList/HyperonPhysics.hh
  simulation/g4simulation/EICPhysicsList/IonPhysics.cc
  simulation/g4simulation/EICPhysicsList/IonPhysics.hh
  simulation/g4simulation/EICPhysicsList/KaonPhysics.cc
  simulation/g4simulation/EICPhysicsList/KaonPhysics.hh
  simulation/g4simulation/EICPhysicsList/Makefile.am
  simulation/g4simulation/EICPhysicsList/NeutronPhysics.cc
  simulation/g4simulation/EICPhysicsList/NeutronPhysics.hh
  simulation/g4simulation/EICPhysicsList/PionPhysics.cc
  simulation/g4simulation/EICPhysicsList/PionPhysics.hh
  simulation/g4simulation/EICPhysicsList/ProtonPhysics.cc
  simulation/g4simulation/EICPhysicsList/ProtonPhysics.hh
  simulation/g4simulation/EICPhysicsList/autogen.sh
  simulation/g4simulation/EICPhysicsList/configure.ac
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4Reco.cc
Labels: CI-build-new-FAIL, CI-build-root6-FAIL, CI-calo-QA-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
