Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2019-03, with the labels that each got.

#595 remove unneeded lib dependencies for libphg4hit
  simulation/g4simulation/g4main/Makefile.am
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#596 Fix cppcheck warnings
  offline/packages/vararray/VariableArray.cc
  simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.cc
  simulation/g4simulation/EICPhysicsList/GammaLeptoNuclearPhysics.cc
  simulation/g4simulation/EICPhysicsList/HyperonPhysics.cc
  simulation/g4simulation/EICPhysicsList/IonPhysics.cc
  simulation/g4simulation/EICPhysicsList/KaonPhysics.cc
  simulation/g4simulation/EICPhysicsList/NeutronPhysics.cc
  simulation/g4simulation/EICPhysicsList/PionPhysics.cc
  simulation/g4simulation/EICPhysicsList/ProtonPhysics.cc
  simulation/g4simulation/g4detectors/PHG4ConeRegionSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CylinderGeomv4.cc
  simulation/g4simulation/g4detectors/PHG4FPbScRegionSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h
  simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.h
  simulation/g4simulation/g4detectors/PHG4ForwardHcalDetector.h
  simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardHcalSubsystem.h
  simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.cc
  simulation/g4simulation/g4detectors/PHG4FullProjSpacalCellReco.h
  simulation/g4simulation/g4detectors/PHG4FullProjSpacalDetector.cc
  simulation/g4simulation/g4detectors/PHG4FullProjSpacalDetector.h
  simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
  simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.h
  simulation/g4simulation/g4detectors/PHG4RICHSubsystem.h
  simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc
  simulation/g4simulation/g4detectors/PHG4SectorConstructor.h
  simulation/g4simulation/g4detectors/PHG4SectorSubsystem.h
  simulation/g4simulation/g4detectors/PHG4mRICHDetector.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4gdml/PHG4GDMLWrite.cc
  simulation/g4simulation/g4gdml/PHG4GDMLWriteMaterials.cc
  simulation/g4simulation/g4gdml/PHG4GDMLWriteSolids.cc
  simulation/g4simulation/g4gdml/PHG4GDMLWriteStructure.cc
  simulation/g4simulation/g4histos/G4RootScintillatorSlatContainer.cc
  simulation/g4simulation/g4histos/G4ScintillatorSlatTTree.cc
  simulation/g4simulation/g4jets/JetReco.cc
  simulation/g4simulation/g4jets/JetReco.h
  simulation/g4simulation/g4main/HepMCNodeReader.cc
  simulation/g4simulation/g4main/PHG4TruthEventAction.cc
  simulation/g4simulation/g4main/ReadEICFiles.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#597 this change makes the cling loading complaint about JetMap.h go away
  simulation/g4simulation/g4jets/JetMapv1LinkDef.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#599 Fix noname node
  offline/framework/phool/PHCompositeNode.cc
  offline/framework/phool/PHCompositeNode.h
  offline/framework/phool/PHDataNode.h
  offline/framework/phool/PHDataNodeIterator.h
  offline/framework/phool/PHFlag.h
  offline/framework/phool/PHFlagLinkDef.h
  offline/framework/phool/PHIODataNode.h
  offline/framework/phool/PHIOManager.h
  offline/framework/phool/PHNode.cc
  offline/framework/phool/PHNode.h
  offline/framework/phool/PHNodeIOManager.cc
  offline/framework/phool/PHNodeIOManager.h
  offline/framework/phool/PHNodeIntegrate.h
  offline/framework/phool/PHNodeIterator.h
  offline/framework/phool/PHNodeOperation.h
  offline/framework/phool/PHNodeReset.h
  offline/framework/phool/PHObject.h
  offline/framework/phool/PHObjectLinkDef.h
  offline/framework/phool/PHOperation.h
  offline/framework/phool/PHPointerList.h
  offline/framework/phool/PHPointerListIterator.h
  offline/framework/phool/PHRandomSeed.h
  offline/framework/phool/PHRandomSeedLinkDef.h
  offline/framework/phool/PHRawDataNode.h
  offline/framework/phool/PHRawOManager.h
  offline/framework/phool/PHTimeServer.h
  offline/framework/phool/PHTimeServerLinkDef.h
  offline/framework/phool/PHTimeStamp.cc
  offline/framework/phool/PHTimeStamp.h
  offline/framework/phool/PHTimeStampLinkDef.h
  offline/framework/phool/PHTimer.h
  offline/framework/phool/PHTypedNodeIterator.h
  offline/framework/phool/getClass.h
  offline/framework/phool/phool.h
  offline/framework/phool/phooldefs.h
  offline/framework/phool/recoConsts.h
  offline/framework/phool/recoConstsLinkDef.h
  simulation/g4simulation/g4jets/Jet.h
  simulation/g4simulation/g4jets/JetMap.h
  simulation/g4simulation/g4jets/JetMapv1LinkDef.h
Labels: CI-build-new-FAIL, CI-build-root6-PASS, CI-calo-QA-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#598 Modified diffusion calculation for MVTX and set a single ADC threshol…
  simulation/g4simulation/g4mvtx/PHG4MVTXCellReco.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXCellReco.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#600 Fix cppcheck
  offline/packages/CaloReco/BEmcCluster.h
  offline/packages/intt/INTTClusterizer.cc
  offline/packages/mvtx/MVTXClusterizer.cc
  simulation/g4simulation/EICPhysicsList/AntiBaryonPhysics.cc
  simulation/g4simulation/g4detectors/PHG4mRICHDetector.cc
  simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc
  simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h
  simulation/g4simulation/g4hough/CellularAutomaton_v1.C
  simulation/g4simulation/g4mvtx/PHG4CylinderCell_MVTX.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#601 INTT new endcap ring geometry using Carbon-PEEK
  simulation/g4simulation/g4intt/PHG4INTTDetector.cc
  simulation/g4simulation/g4intt/PHG4INTTSubsystem.cc
  simulation/g4simulation/g4main/PHG4Reco.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#602 Add Memory tracking
  offline/framework/fun4all/Fun4AllMemoryTracker.cc
  offline/framework/fun4all/Fun4AllMemoryTracker.h
  offline/framework/fun4all/Fun4AllServer.cc
  offline/framework/fun4all/Fun4AllServer.h
  offline/framework/fun4all/Makefile.am
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#604 Private datamembers for Fun4AllFileOutStream
  offline/framework/fun4all/Fun4AllFileOutStream.cc
  offline/framework/fun4all/Fun4AllFileOutStream.h
  offline/framework/fun4all/Fun4AllRolloverFileOutStream.cc
  offline/framework/fun4all/Fun4AllRolloverFileOutStream.h
  simulation/g4simulation/g4main/PHG4SteppingAction.cc
  simulation/g4simulation/g4main/PHG4SteppingAction.h
  simulation/g4simulation/g4main/ReadEICFiles.cc
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#605 Accumulated fixes on the EIC/fsPHENIX fast tracking module - coresoftware repository
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h
  simulation/g4simulation/g4hough/Makefile.am
  simulation/g4simulation/g4hough/PHG4TrackFastSim.C
  simulation/g4simulation/g4hough/PHG4TrackFastSim.h
  simulation/g4simulation/g4trackfastsim/Makefile.am
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.cc
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEval.h
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimEvalLinkDef.h
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSimLinkDef.h
  simulation/g4simulation/g4trackfastsim/autogen.sh
  simulation/g4simulation/g4trackfastsim/configure.ac
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#606 add eigen include dir to include path
  simulation/g4simulation/g4trackfastsim/Makefile.am
Labels: CI-build-new-PENDING, CI-build-root6-PENDING, CI-calo-QA-PENDING, CI-cpp-check-PENDING, CI-valgrind-PENDING

#607 Private datamembers
  generators/phhepmc/Fun4AllHepMCInputManager.cc
  generators/phhepmc/Fun4AllHepMCInputManager.h
  generators/phhepmc/Fun4AllHepMCPileupInputManager.cc
  generators/phhepmc/Fun4AllOscarInputManager.cc
  generators/phhepmc/Fun4AllOscarInputManager.h
  offline/framework/fun4all/Fun4AllBaseLinkDef.h
  offline/framework/fun4all/Fun4AllDstInputManager.cc
  offline/framework/fun4all/Fun4AllDstInputManager.h
  offline/framework/fun4all/Fun4AllDstInputManagerLinkDef.h
  offline/framework/fun4all/Fun4AllDstOutputManager.cc
  offline/framework/fun4all/Fun4AllDstOutputManager.h
  offline/framework/fun4all/Fun4AllDstOutputManagerLinkDef.h
  offline/framework/fun4all/Fun4AllDummyInputManager.cc
  offline/framework/fun4all/Fun4AllDummyInputManager.h
  offline/framework/fun4all/Fun4AllDummyInputManagerLinkDef.h
  offline/framework/fun4all/Fun4AllEventOutStream.cc
  offline/framework/fun4all/Fun4AllEventOutStream.h
  offline/framework/fun4all/Fun4AllEventOutputManager.cc
  offline/framework/fun4all/Fun4AllEventOutputManager.h
  offline/framework/fun4all/Fun4AllFileOutStream.cc
  offline/framework/fun4all/Fun4AllHistoBinDefs.h
  offline/framework/fun4all/Fun4AllHistoManager.cc
  offline/framework/fun4all/Fun4AllHistoManager.h
  offline/framework/fun4all/Fun4AllHistoManagerLinkDef.h
  offline/framework/fun4all/Fun4AllInputManager.cc
  offline/framework/fun4all/Fun4AllInputManager.h
  offline/framework/fun4all/Fun4AllInputManagerLinkDef.h
  offline/framework/fun4all/Fun4AllMemoryTracker.h
  offline/framework/fun4all/Fun4AllNoSyncDstInputManager.cc
  offline/framework/fun4all/Fun4AllNoSyncDstInputManager.h
  offline/framework/fun4all/Fun4AllNoSyncDstInputManagerLinkDef.h
  offline/framework/fun4all/Fun4AllOutputManager.h
  offline/framework/fun4all/Fun4AllOutputManagerLinkDef.h
  offline/framework/fun4all/Fun4AllPrdfInputManager.cc
  offline/framework/fun4all/Fun4AllPrdfInputManager.h
  offline/framework/fun4all/Fun4AllPrdfInputManagerLinkDef.h
  offline/framework/fun4all/Fun4AllPrdfOutputManager.cc
  offline/framework/fun4all/Fun4AllPrdfOutputManager.h
  offline/framework/fun4all/Fun4AllPrdfOutputManagerLinkDef.h
  offline/framework/fun4all/Fun4AllReturnCodes.h
  offline/framework/fun4all/Fun4AllRolloverFileOutStream.cc
  offline/framework/fun4all/Fun4AllRolloverFileOutStream.h
  offline/framework/fun4all/Fun4AllServer.cc
  offline/framework/fun4all/Fun4AllServerLinkDef.h
  offline/framework/fun4all/Fun4AllSyncManager.cc
  offline/framework/fun4all/Fun4AllSyncManager.h
  offline/framework/fun4all/Fun4AllSyncManagerLinkDef.h
  offline/framework/fun4all/Fun4AllUtils.cc
  offline/framework/fun4all/Fun4AllUtils.h
  offline/framework/fun4all/Makefile.am
  offline/framework/fun4all/PHTFileServer.cc
  offline/framework/fun4all/PHTFileServer.h
  offline/framework/fun4all/RunNumberRanges.h
  offline/framework/fun4all/SubsysReco.cc
  offline/framework/fun4all/SubsysReco.h
  offline/framework/fun4all/SubsysRecoLinkDef.h
  offline/framework/fun4all/TDirectoryHelper.cc
  offline/framework/fun4all/TDirectoryHelper.h
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#608 install ReadEICFiles.h
  simulation/g4simulation/g4main/Makefile.am
Labels: CI-build-new-PASS, CI-build-root6-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#609 Fix tutorials
  offline/framework/fun4all/Fun4AllMemoryTracker.cc
  offline/framework/fun4all/Fun4AllMemoryTracker.h
  simulation/g4simulation/g4histos/Makefile.am
Labels: CI-build-new-FAIL, CI-build-root6-PASS, CI-calo-QA-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#610 INTT new stave design (version Mar12)
  simulation/g4simulation/g4intt/PHG4INTTDetector.cc
  simulation/g4simulation/g4intt/PHG4INTTSubsystem.cc
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#611 Fix parameter ordering issue when using G4GenericTrap for INTT geometry
  simulation/g4simulation/g4intt/PHG4INTTDetector.cc
Labels: CI-build-new-PENDING, CI-build-root5-PENDING, CI-cpp-check-AVAILABLE, CI-valgrind-PENDING

#612 Apply Tony's fix to cure infinite loop on tracking
  offline/packages/trackreco/PHGenFitTrkProp.cc
Labels: CI-build-new-PASS, CI-build-root5-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#613 Calorimeter standard QA -> ROOT6
  offline/QA/macros/QA_Draw_ALL.sh
  offline/QA/macros/QA_Draw_CEMC_G4Hit.C
  offline/QA/macros/QA_Draw_CEMC_TowerCluster.C
  offline/QA/macros/QA_Draw_Calorimeter_Sum_Cluster.C
  offline/QA/macros/QA_Draw_Calorimeter_Sum_TrackProj.C
  offline/QA/macros/QA_Draw_Calorimeter_Sum_TrackProjEP.C
  offline/QA/macros/QA_Draw_HCALIN_G4Hit.C
  offline/QA/macros/QA_Draw_HCALIN_TowerCluster.C
  offline/QA/macros/QA_Draw_HCALOUT_G4Hit.C
  offline/QA/macros/QA_Draw_HCALOUT_TowerCluster.C
  offline/QA/macros/QA_Draw_Jet_Spectrum.C
  offline/QA/macros/QA_Draw_Jet_Summary.C
  offline/QA/macros/QA_Draw_Jet_TruthMatching.C
  offline/QA/macros/QA_Draw_Utility.C
  offline/QA/macros/SaveCanvas.C
  offline/QA/macros/SetOKStyle.C
  offline/QA/modules/Makefile.am
  offline/QA/modules/QAG4SimulationCalorimeter.cc
  offline/framework/fun4all/Fun4AllHistoManager.cc
  offline/framework/fun4all/Fun4AllHistoManager.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
