Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2019-05, with the labels that each got.

#630 New DisplayAction
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4CEmcTestBeamSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4ConeSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc
  simulation/g4simulation/g4detectors/PHG4CylinderDetector.h
  simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.h
  simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.h
  simulation/g4simulation/g4detectors/PHG4EnvelopeSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4ForwardHcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4HcalPrototypeSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4HcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4RICHSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4SectorSubsystem.cc
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4DisplayAction.cc
  simulation/g4simulation/g4main/PHG4DisplayAction.h
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4main/PHG4Reco.h
  simulation/g4simulation/g4main/PHG4Subsystem.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#632 Mvtx leak
  simulation/g4simulation/g4mvtx/Makefile.am
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizerLinkDef.h
  simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxDigitizerLinkDef.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#633 Display Actions for hcals
  offline/database/PHParameter/PHParameterInterface.cc
  offline/database/PHParameter/PHParameterInterface.h
  offline/database/PHParameter/PHParameters.cc
  offline/database/PHParameter/PHParameters.h
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4BlockDetector.cc
  simulation/g4simulation/g4detectors/PHG4BlockDetector.h
  simulation/g4simulation/g4detectors/PHG4BlockDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4BlockDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4BlockSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4BlockSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CEmcTestBeamSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc
  simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc
  simulation/g4simulation/g4detectors/PHG4CylinderDetector.h
  simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4CylinderDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CylinderSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4EnvelopeSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4FPbScSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4HcalPrototypeSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h
  simulation/g4simulation/g4detectors/PHG4InnerHcalDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.h
  simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.h
  simulation/g4simulation/g4detectors/PHG4OuterHcalDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4OuterHcalField.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.h
  simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4Prototype2OuterHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4Prototype3InnerHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4SectorSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4SpacalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4mRICHSteppingAction.cc
  simulation/g4simulation/g4intt/PHG4INTTSteppingAction.cc
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4SteppingAction.cc
  simulation/g4simulation/g4main/PHG4SteppingAction.h
  simulation/g4simulation/g4main/PHG4TruthSteppingAction.cc
  simulation/g4simulation/g4main/PHG4TruthSteppingAction.h
  simulation/g4simulation/g4main/PHG4TruthSubsystem.cc
  simulation/g4simulation/g4main/PHG4TruthSubsystem.h
  simulation/g4simulation/g4mvtx/PHG4MVTXSteppingAction.cc
  simulation/g4simulation/g4tpc/PHG4TPCSteppingAction.cc
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#634 Fix autotools
  offline/packages/HelixHough/FitNewton/AUTHORS
  offline/packages/HelixHough/FitNewton/ChangeLog
  offline/packages/HelixHough/FitNewton/Makefile.am
  offline/packages/HelixHough/FitNewton/NEWS
  offline/packages/HelixHough/FitNewton/README
  offline/packages/HelixHough/FitNewton/build.sh
  offline/packages/HelixHough/FitNewton/configure.ac
  offline/packages/HelixHough/FitNewton/fitnewton.pc.in
  offline/packages/HelixHough/FitNewton/pkg.m4
  offline/packages/HelixHough/Seamstress/AUTHORS
  offline/packages/HelixHough/Seamstress/ChangeLog
  offline/packages/HelixHough/Seamstress/Makefile.am
  offline/packages/HelixHough/Seamstress/NEWS
  offline/packages/HelixHough/Seamstress/README
  offline/packages/HelixHough/Seamstress/build.sh
  offline/packages/HelixHough/Seamstress/configure.ac
  offline/packages/HelixHough/Seamstress/seamstress.pc.in
  offline/packages/HelixHough/configure.ac
  offline/packages/HelixHough/helix_hough/AUTHORS
  offline/packages/HelixHough/helix_hough/ChangeLog
  offline/packages/HelixHough/helix_hough/Makefile.am
  offline/packages/HelixHough/helix_hough/NEWS
  offline/packages/HelixHough/helix_hough/README
  offline/packages/HelixHough/helix_hough/configure.ac
  offline/packages/HelixHough/helix_hough/helix_hough.pc.in
  offline/packages/HelixHough/helix_hough/pkg.m4
  offline/packages/NodeDump/DumpTrkrClusterContainer.cc
  offline/packages/NodeDump/DumpTrkrClusterContainer.h
  offline/packages/NodeDump/DumpTrkrHitSetContainer.cc
  offline/packages/NodeDump/DumpTrkrHitSetContainer.h
  offline/packages/NodeDump/Makefile.am
  offline/packages/NodeDump/PHNodeDump.cc
  offline/packages/trackbase/TrkrHitSet.h
  offline/packages/trackbase/TrkrHitTruthAssoc.h
  simulation/g4simulation/g4tpc/Makefile.am
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#635 Mvtx displayaction
  simulation/g4simulation/g4main/PHG4DisplayAction.h
  simulation/g4simulation/g4mvtx/Makefile.am
  simulation/g4simulation/g4mvtx/PHG4MVTXDetector.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDetector.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDisplayAction.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDisplayAction.h
  simulation/g4simulation/g4mvtx/PHG4MVTXSteppingAction.h
  simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#636 Mvtx Eventaction replacement
  simulation/g4simulation/g4mvtx/PHG4MVTXDetector.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDetector.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDisplayAction.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDisplayAction.h
  simulation/g4simulation/g4mvtx/PHG4MVTXSteppingAction.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXSteppingAction.h
  simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#637 Displayaction intt
  simulation/g4simulation/g4intt/Makefile.am
  simulation/g4simulation/g4intt/PHG4INTTDetector.cc
  simulation/g4simulation/g4intt/PHG4INTTDetector.h
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.cc
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.h
  simulation/g4simulation/g4intt/PHG4INTTDigitizerLinkDef.h
  simulation/g4simulation/g4intt/PHG4INTTDisplayAction.cc
  simulation/g4simulation/g4intt/PHG4INTTDisplayAction.h
  simulation/g4simulation/g4intt/PHG4INTTFPHXParameterisation.cc
  simulation/g4simulation/g4intt/PHG4INTTFPHXParameterisation.h
  simulation/g4simulation/g4intt/PHG4INTTSubsystem.cc
  simulation/g4simulation/g4intt/PHG4INTTSubsystem.h
  simulation/g4simulation/g4tpc/Makefile.am
  simulation/g4simulation/g4tpc/PHG4TPCDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TPCDigitizer.h
  simulation/g4simulation/g4tpc/PHG4TPCDigitizerLinkDef.h
  simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TPCElectronDriftLinkDef.h
Labels: CI-DST-readback-AVAILABLE, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#638 Fix leak
  simulation/g4simulation/g4intt/PHG4INTTDeadMapLoader.cc
  simulation/g4simulation/g4intt/PHG4INTTDetector.cc
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.cc
  simulation/g4simulation/g4intt/PHG4INTTParameterisation.cc
  simulation/g4simulation/g4intt/PHG4INTTParameterisation.h
  simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
  simulation/g4simulation/g4intt/PHG4InttDigitizer.h
  simulation/g4simulation/g4intt/PHG4InttDigitizerLinkDef.h
  simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h
  simulation/g4simulation/g4tpc/PHG4TpcDigitizerLinkDef.h
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TpcElectronDriftLinkDef.h
Labels: CI-DST-readback-AVAILABLE, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#639 DisplayAction for the tpc
  simulation/g4simulation/g4intt/PHG4INTTDisplayAction.h
  simulation/g4simulation/g4tpc/Makefile.am
  simulation/g4simulation/g4tpc/PHG4TPCDetector.cc
  simulation/g4simulation/g4tpc/PHG4TPCDetector.h
  simulation/g4simulation/g4tpc/PHG4TPCDisplayAction.cc
  simulation/g4simulation/g4tpc/PHG4TPCDisplayAction.h
  simulation/g4simulation/g4tpc/PHG4TPCPadPlaneReadout.cc
  simulation/g4simulation/g4tpc/PHG4TPCSubsystem.cc
  simulation/g4simulation/g4tpc/PHG4TPCSubsystem.h
Labels: CI-DST-readback-AVAILABLE, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#640 Displayaction for Spacal
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.cc
  simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv1.h
  simulation/g4simulation/g4detectors/PHG4FullProjSpacalDetector.cc
  simulation/g4simulation/g4detectors/PHG4FullProjSpacalDetector.h
  simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
  simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.h
  simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4Prototype2InnerHcalDetector.h
  simulation/g4simulation/g4detectors/PHG4SpacalDetector.cc
  simulation/g4simulation/g4detectors/PHG4SpacalDetector.h
  simulation/g4simulation/g4detectors/PHG4SpacalDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4SpacalDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4SpacalPrototypeDetector.h
  simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.h
  simulation/g4simulation/g4tpc/PHG4TPCDisplayAction.cc
Labels: CI-DST-readback-AVAILABLE, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#641 Displayaction fsphenix
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4EICForwardEcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4EICForwardEcalDetector.h
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDetector.h
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4ForwardEcalSubsystem.h
  simulation/g4simulation/g4detectors/PHG4ForwardHcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4ForwardHcalDetector.h
  simulation/g4simulation/g4detectors/PHG4ForwardHcalDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardHcalDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ForwardHcalSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4ForwardHcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4ForwardHcalSubsystem.h
  simulation/g4simulation/g4detectors/PHG4SectorConstructor.cc
  simulation/g4simulation/g4detectors/PHG4SectorConstructor.h
  simulation/g4simulation/g4detectors/PHG4SectorDetector.cc
  simulation/g4simulation/g4detectors/PHG4SectorDetector.h
  simulation/g4simulation/g4detectors/PHG4SectorDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4SectorDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4SectorSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4SectorSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4SectorSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4SectorSubsystem.h
  simulation/g4simulation/g4detectors/PHG4SpacalPrototypeDetector.h
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4PhenixDetector.cc
  simulation/g4simulation/g4main/PHG4PhenixDetector.h
  simulation/g4simulation/g4main/PHG4PhenixDisplayAction.cc
  simulation/g4simulation/g4main/PHG4PhenixDisplayAction.h
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4main/PHG4Reco.h
Labels: CI-DST-readback-AVAILABLE, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#642 Displayaction eic
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.h
  simulation/g4simulation/g4detectors/PHG4RICHDetector.cc
  simulation/g4simulation/g4detectors/PHG4RICHDetector.h
  simulation/g4simulation/g4detectors/PHG4RICHDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4RICHDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4RICHSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4RICHSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4RICHSubsystem.h
  simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc
  simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h
Labels: CI-DST-readback-AVAILABLE, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#644 Truth tracking
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHTruthTrackSeeding.cc
  offline/packages/trackreco/PHTruthTrackSeeding.h
Labels: CI-DST-readback-PASS, CI-build-new-FAIL, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-FAIL

#629 Add two layer TPC central membrane surface material with Cu+PCB
  simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
  simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#646 Iwyu qa
  generators/sHijing/xml_test.C
  offline/QA/modules/QAG4SimulationCalorimeter.cc
  offline/QA/modules/QAG4SimulationCalorimeter.h
  offline/QA/modules/QAG4SimulationCalorimeterSum.cc
  offline/QA/modules/QAG4SimulationCalorimeterSum.h
  offline/QA/modules/QAG4SimulationJet.cc
  offline/QA/modules/QAG4SimulationJet.h
  offline/QA/modules/QAHistManagerDef.cc
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#647 Iwyu vararray
  offline/packages/CaloBase/RawCluster.cc
  offline/packages/CaloBase/RawCluster.h
  offline/packages/CaloBase/RawClusterContainer.h
  offline/packages/CaloBase/RawClusterv1.cc
  offline/packages/CaloBase/RawClusterv1.h
  offline/packages/CaloBase/RawTowerContainer.h
  offline/packages/CaloBase/RawTowerDeadMap.h
  offline/packages/CaloBase/RawTowerDeadMapv1.cc
  offline/packages/CaloBase/RawTowerDeadMapv1.h
  offline/packages/CaloBase/RawTowerGeom.cc
  offline/packages/CaloBase/RawTowerGeom.h
  offline/packages/CaloBase/RawTowerGeomContainer.h
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.cc
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h
  offline/packages/CaloBase/RawTowerGeomContainerv1.h
  offline/packages/CaloBase/RawTowerGeomv1.h
  offline/packages/CaloBase/RawTowerGeomv2.h
  offline/packages/CaloBase/RawTowerGeomv3.h
  offline/packages/CaloBase/RawTowerv1.h
  offline/packages/CaloReco/BEmcCluster.cc
  offline/packages/CaloReco/BEmcCluster.h
  offline/packages/CaloReco/BEmcRec.cc
  offline/packages/CaloReco/BEmcRecCEMC.cc
  offline/packages/CaloReco/BEmcRecEEMC.cc
  offline/packages/CaloReco/BEmcRecFEMC.cc
  offline/packages/CaloReco/RawClusterBuilderFwd.cc
  offline/packages/CaloReco/RawClusterBuilderGraph.cc
  offline/packages/CaloReco/RawClusterBuilderGraph.h
  offline/packages/CaloReco/RawClusterBuilderTemplate.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.h
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.h
  offline/packages/CaloReco/RawClusterDeadAreaMask.cc
  offline/packages/CaloReco/RawClusterDeadAreaMask.h
  offline/packages/CaloReco/RawClusterPositionCorrection.cc
  offline/packages/CaloReco/RawClusterPositionCorrection.h
  offline/packages/CaloReco/RawTowerCalibration.cc
  offline/packages/CaloReco/RawTowerCombiner.cc
  offline/packages/CaloReco/RawTowerCombiner.h
  offline/packages/CaloReco/RawTowerDeadMapLoader.cc
  offline/packages/CaloReco/RawTowerDeadMapLoader.h
  offline/packages/CaloReco/RawTowerDeadTowerInterp.cc
  offline/packages/ClusterIso/ClusterIso.cc
  offline/packages/ClusterIso/ClusterIso.h
  offline/packages/trigger/CaloTriggerInfov1.cc
  offline/packages/trigger/CaloTriggerInfov1.h
  offline/packages/trigger/CaloTriggerSim.cc
  offline/packages/trigger/CaloTriggerSim.h
  offline/packages/vararray/VariableArray.cc
  offline/packages/vararray/VariableArray.h
  offline/packages/vararray/VariableArrayContainer.h
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#648 Iwyu g4eval
  offline/packages/CaloBase/RawTowerGeomContainerv1.cc
  offline/packages/jetbackground/CopyAndSubtractJets.cc
  offline/packages/jetbackground/CopyAndSubtractJets.h
  offline/packages/jetbackground/DetermineTowerBackground.cc
  offline/packages/jetbackground/DetermineTowerBackground.h
  offline/packages/jetbackground/FastJetAlgoSub.cc
  offline/packages/jetbackground/FastJetAlgoSub.h
  offline/packages/jetbackground/RetowerCEMC.cc
  offline/packages/jetbackground/RetowerCEMC.h
  offline/packages/jetbackground/SubtractTowers.cc
  offline/packages/jetbackground/SubtractTowers.h
  offline/packages/jetbackground/SubtractTowersCS.cc
  offline/packages/jetbackground/SubtractTowersCS.h
  offline/packages/jetbackground/TowerBackgroundv1.cc
  offline/packages/jetbackground/TowerBackgroundv1.h
  simulation/g4simulation/g4eval/BaseTruthEval.cc
  simulation/g4simulation/g4eval/CaloEvalStack.h
  simulation/g4simulation/g4eval/CaloEvaluator.cc
  simulation/g4simulation/g4eval/CaloEvaluator.h
  simulation/g4simulation/g4eval/CaloRawClusterEval.cc
  simulation/g4simulation/g4eval/CaloRawClusterEval.h
  simulation/g4simulation/g4eval/CaloRawTowerEval.cc
  simulation/g4simulation/g4eval/CaloRawTowerEval.h
  simulation/g4simulation/g4eval/CaloTruthEval.cc
  simulation/g4simulation/g4eval/JetEvalStack.h
  simulation/g4simulation/g4eval/JetEvaluator.cc
  simulation/g4simulation/g4eval/JetEvaluator.h
  simulation/g4simulation/g4eval/JetRecoEval.cc
  simulation/g4simulation/g4eval/JetRecoEval.h
  simulation/g4simulation/g4eval/JetTruthEval.cc
  simulation/g4simulation/g4eval/JetTruthEval.h
  simulation/g4simulation/g4eval/MomentumEvaluator.cc
  simulation/g4simulation/g4eval/MomentumEvaluator.h
  simulation/g4simulation/g4eval/PHG4DSTReader.cc
  simulation/g4simulation/g4eval/PHG4DSTReader.h
  simulation/g4simulation/g4eval/PHG4DstCompressReco.cc
  simulation/g4simulation/g4eval/SvtxClusterEval.cc
  simulation/g4simulation/g4eval/SvtxClusterEval.h
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.h
  simulation/g4simulation/g4eval/SvtxHitEval.cc
  simulation/g4simulation/g4eval/SvtxHitEval.h
  simulation/g4simulation/g4eval/SvtxTrackEval.cc
  simulation/g4simulation/g4eval/SvtxTrackEval.h
  simulation/g4simulation/g4eval/SvtxTruthEval.cc
  simulation/g4simulation/g4eval/SvtxVertexEval.cc
  simulation/g4simulation/g4eval/SvtxVertexEval.h
  simulation/g4simulation/g4eval/TrkrEvaluator.cc
  simulation/g4simulation/g4eval/TrkrEvaluator.h
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#649 Iwyu nodedump
  offline/packages/NodeDump/DumpBbcVertexMap.cc
  offline/packages/NodeDump/DumpCaloTriggerInfo.cc
  offline/packages/NodeDump/DumpGlobalVertexMap.cc
  offline/packages/NodeDump/DumpJetMap.cc
  offline/packages/NodeDump/DumpObject.cc
  offline/packages/NodeDump/DumpObject.h
  offline/packages/NodeDump/DumpPHG4BlockCellGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4BlockGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4CellContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderCellContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderCellGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4HitContainer.cc
  offline/packages/NodeDump/DumpPHG4InEvent.cc
  offline/packages/NodeDump/DumpPHG4ScintillatorSlatContainer.cc
  offline/packages/NodeDump/DumpPHG4TruthInfoContainer.cc
  offline/packages/NodeDump/DumpPdbParameterMap.cc
  offline/packages/NodeDump/DumpPdbParameterMapContainer.cc
  offline/packages/NodeDump/DumpRawClusterContainer.cc
  offline/packages/NodeDump/DumpRawTowerContainer.cc
  offline/packages/NodeDump/DumpRawTowerGeom.cc
  offline/packages/NodeDump/DumpRawTowerGeomContainer.cc
  offline/packages/NodeDump/DumpRunHeader.cc
  offline/packages/NodeDump/DumpSvtxClusterMap.cc
  offline/packages/NodeDump/DumpSvtxHitMap.cc
  offline/packages/NodeDump/DumpSvtxTrackMap.cc
  offline/packages/NodeDump/DumpSvtxVertexMap.cc
  offline/packages/NodeDump/DumpSyncObject.cc
  offline/packages/NodeDump/DumpTowerBackground.cc
  offline/packages/NodeDump/DumpTrkrClusterContainer.cc
  offline/packages/NodeDump/DumpTrkrHitSetContainer.cc
  offline/packages/NodeDump/DumpVariableArray.cc
  offline/packages/NodeDump/DumpVariableArrayInt.cc
  offline/packages/NodeDump/Dumper.cc
  offline/packages/NodeDump/PHNodeDump.cc
  simulation/g4simulation/g4detectors/PHG4Cell.h
  simulation/g4simulation/g4detectors/PHG4CylinderCell.h
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#650 Iwyu helixhough phfield
  offline/packages/HelixHough/FitNewton/ChiSquareGradHessian.cpp
  offline/packages/HelixHough/FitNewton/ChiSquareGradHessian.h
  offline/packages/HelixHough/FitNewton/GaussianGradHessian.cpp
  offline/packages/HelixHough/FitNewton/GaussianGradHessian.h
  offline/packages/HelixHough/FitNewton/GaussianIntegralGradHessian.cpp
  offline/packages/HelixHough/FitNewton/GaussianIntegralGradHessian.h
  offline/packages/HelixHough/FitNewton/GaussianRegGradHessian.cpp
  offline/packages/HelixHough/FitNewton/GaussianRegGradHessian.h
  offline/packages/HelixHough/FitNewton/NewtonMinimizerGradHessian.cpp
  offline/packages/HelixHough/FitNewton/NewtonMinimizerGradHessian.h
  offline/packages/HelixHough/FitNewton/SquareGradient.cpp
  offline/packages/HelixHough/FitNewton/SquareGradient.h
  offline/packages/HelixHough/Seamstress/Pincushion.h
  offline/packages/HelixHough/Seamstress/Seamstress.cpp
  offline/packages/HelixHough/Seamstress/Seamstress.h
  offline/packages/HelixHough/helix_hough/HelixHough_allButKappaRange_sse.cpp
  offline/packages/HelixHough/helix_hough/HelixHough_dzdlRange_sse.cpp
  offline/packages/HelixHough/helix_hough/HelixHough_findHelices.cpp
  offline/packages/HelixHough/helix_hough/HelixHough_findPairs.cpp
  offline/packages/HelixHough/helix_hough/HelixHough_init.cpp
  offline/packages/HelixHough/helix_hough/HelixHough_phiRange_sse.cpp
  offline/packages/HelixHough/helix_hough/HelixHough_split.cpp
  offline/packages/HelixHough/helix_hough/HelixHough_vote_pairs_sse.cpp
  offline/packages/HelixHough/helix_hough/HelixHough_vote_sse.cpp
  offline/packages/HelixHough/helix_hough/Kalman/CylinderKalman.cpp
  offline/packages/HelixHough/helix_hough/Kalman/CylinderKalman.h
  offline/packages/HelixHough/helix_hough/Kalman/HelixKalman.cpp
  offline/packages/HelixHough/helix_hough/Kalman/HelixKalman.h
  offline/packages/HelixHough/helix_hough/Kalman/HelixKalmanState.h
  offline/packages/HelixHough/helix_hough/SimpleHit3D.cpp
  offline/packages/HelixHough/helix_hough/SimpleHit3D.h
  offline/packages/HelixHough/helix_hough/VertexFinder.cpp
  offline/packages/HelixHough/helix_hough/VertexFinder.h
  offline/packages/HelixHough/helix_hough/VertexFitFunc.cpp
  offline/packages/HelixHough/helix_hough/VertexFitFunc.h
  offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXSeedFinder.cpp
  offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXSeedFinder.h
  offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTracker.cpp
  offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTracker.h
  offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTrackerTpc.cpp
  offline/packages/HelixHough/helix_hough/sPHENIX/sPHENIXTrackerTpc.h
  offline/packages/NodeDump/Dumper.h
  offline/packages/PHField/PHField2D.cc
  offline/packages/PHField/PHField2D.h
  offline/packages/PHField/PHField3DCartesian.cc
  offline/packages/PHField/PHField3DCartesian.h
  offline/packages/PHField/PHField3DCylindrical.cc
  offline/packages/PHField/PHField3DCylindrical.h
  offline/packages/PHField/PHFieldConfig.cc
  offline/packages/PHField/PHFieldConfig.h
  offline/packages/PHField/PHFieldConfigv1.cc
  offline/packages/PHField/PHFieldConfigv1.h
  offline/packages/PHField/PHFieldConfigv2.cc
  offline/packages/PHField/PHFieldConfigv2.h
  offline/packages/PHField/PHFieldUniform.cc
  offline/packages/PHField/PHFieldUniform.h
  offline/packages/PHField/PHFieldUtility.cc
  offline/packages/PHField/PHFieldUtility.h
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#651 Iwyu genfitexp phgeometry
  offline/packages/PHGenFitPkg/GenFitExp/Field.cc
  offline/packages/PHGenFitPkg/GenFitExp/Field.h
  offline/packages/PHGenFitPkg/PHGenFit/Fitter.cc
  offline/packages/PHGenFitPkg/PHGenFit/Fitter.h
  offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.cc
  offline/packages/PHGenFitPkg/PHGenFit/PlanarMeasurement.h
  offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.cc
  offline/packages/PHGenFitPkg/PHGenFit/SpacepointMeasurement.h
  offline/packages/PHGenFitPkg/PHGenFit/Tools.cc
  offline/packages/PHGenFitPkg/PHGenFit/Track.cc
  offline/packages/PHGenFitPkg/PHGenFit/Track.h
  offline/packages/PHGeometry/PHGeomFileImport.cc
  offline/packages/PHGeometry/PHGeomFileImport.h
  offline/packages/PHGeometry/PHGeomIOTGeo.cc
  offline/packages/PHGeometry/PHGeomIOTGeo.h
  offline/packages/PHGeometry/PHGeomTGeo.cc
  offline/packages/PHGeometry/PHGeomTGeo.h
  offline/packages/PHGeometry/PHGeomUtility.cc
  offline/packages/PHGeometry/PHGeomUtility.h
  offline/packages/intt/CylinderGeomIntt.cc
  offline/packages/intt/CylinderGeomIntt.h
  offline/packages/intt/InttClusterizer.cc
  offline/packages/intt/InttClusterizer.h
  offline/packages/intt/InttDefs.cc
  offline/packages/intt/InttDefs.h
  offline/packages/intt/InttHit.cc
  offline/packages/intt/InttHit.h
  offline/packages/mvtx/CylinderGeom_Mvtx.cc
  offline/packages/mvtx/CylinderGeom_Mvtx.h
  offline/packages/mvtx/MvtxClusterizer.cc
  offline/packages/mvtx/MvtxDefs.cc
  offline/packages/mvtx/MvtxDefs.h
  offline/packages/mvtx/MvtxHit.cc
  offline/packages/mvtx/MvtxHit.h
  offline/packages/tpc/TpcClusterizer.cc
  offline/packages/tpc/TpcClusterizer.h
  offline/packages/tpc/TpcDefs.cc
  offline/packages/tpc/TpcDefs.h
  offline/packages/tpc/TpcHit.cc
  offline/packages/tpc/TpcHit.h
Labels: CI-DST-readback-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
