Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2019-04, with the labels that each got.

#615 Add Ion gun
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4IonGun.cc
  simulation/g4simulation/g4main/PHG4IonGun.h
  simulation/g4simulation/g4main/PHG4IonGunLinkDef.h
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4main/PHG4Reco.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#616 install some more includes for root6
  simulation/g4simulation/g4histos/Makefile.am
  simulation/g4simulation/g4main/PHG4IonGun.cc
  simulation/g4simulation/g4main/PHG4IonGun.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#617 Fix g4dst
  simulation/g4simulation/g4dst/Makefile.am
  simulation/g4simulation/g4eval/Makefile.am
  simulation/g4simulation/g4mvtx/Makefile.am
  simulation/g4simulation/g4mvtx/PHG4CylinderGeom_MVTX.cc
  simulation/g4simulation/g4mvtx/PHG4CylinderGeom_MVTX.h
Labels: CI-build-new-PENDING, CI-build-root5-PENDING, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-PENDING

#618 remove duplicate creation of dictionaries for root5
  offline/packages/intt/Makefile.am
  offline/packages/mvtx/Makefile.am
  offline/packages/tpc/Makefile.am
Labels: CI-build-new-FAIL, CI-build-root5-PASS, CI-calo-QA-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#619 Iongun
  simulation/g4simulation/g4main/G4TBMagneticFieldSetup.cc
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4HitContainer.cc
  simulation/g4simulation/g4main/PHG4InEventCompress.cc
  simulation/g4simulation/g4main/PHG4IonGun.cc
  simulation/g4simulation/g4main/PHG4IonGun.h
  simulation/g4simulation/g4main/PHG4Particle.cc
  simulation/g4simulation/g4main/PHG4Particle.h
  simulation/g4simulation/g4main/PHG4ParticleGenerator.cc
  simulation/g4simulation/g4main/PHG4ParticleGenerator.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.cc
  simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorBaseLinkDef.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.cc
  simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorD0LinkDef.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorLinkDef.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc
  simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMesonLinkDef.h
  simulation/g4simulation/g4main/PHG4ParticleGun.cc
  simulation/g4simulation/g4main/PHG4ParticleGun.h
  simulation/g4simulation/g4main/PHG4ParticleGunLinkDef.h
  simulation/g4simulation/g4main/PHG4ParticleLinkDef.h
  simulation/g4simulation/g4main/PHG4Particlev1.cc
  simulation/g4simulation/g4main/PHG4Particlev1.h
  simulation/g4simulation/g4main/PHG4Particlev1LinkDef.h
  simulation/g4simulation/g4main/PHG4Particlev2.cc
  simulation/g4simulation/g4main/PHG4Particlev2.h
  simulation/g4simulation/g4main/PHG4Particlev2LinkDef.h
  simulation/g4simulation/g4main/PHG4Particlev3.cc
  simulation/g4simulation/g4main/PHG4Particlev3.h
  simulation/g4simulation/g4main/PHG4Particlev3LinkDef.h
  simulation/g4simulation/g4main/PHG4PileupGenerator.cc
  simulation/g4simulation/g4main/PHG4PrimaryGeneratorAction.cc
  simulation/g4simulation/g4main/PHG4PrimaryGeneratorAction.h
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4main/PHG4Reco.h
  simulation/g4simulation/g4main/PHG4Shower.h
  simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc
  simulation/g4simulation/g4main/PHG4TrackUserInfoV1.cc
  simulation/g4simulation/g4main/PHG4TrackUserInfoV1.h
  simulation/g4simulation/g4main/PHG4TruthInfoContainer.cc
  simulation/g4simulation/g4main/PHG4TruthSubsystem.cc
  simulation/g4simulation/g4main/PHG4TruthTrackingAction.cc
  simulation/g4simulation/g4main/PHG4TruthTrackingAction.h
  simulation/g4simulation/g4main/PHG4UIsession.cc
  simulation/g4simulation/g4main/ReadEICFiles.cc
Labels: CI-build-new-FAIL, CI-build-root5-PASS, CI-calo-QA-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#620 Fix library dependencies
  offline/packages/intt/CylinderGeomINTT.cc
  offline/packages/intt/Makefile.am
  offline/packages/jetbackground/Makefile.am
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4dst/Makefile.am
  simulation/g4simulation/g4eval/Makefile.am
  simulation/g4simulation/g4hough/Makefile.am
  simulation/g4simulation/g4intt/Makefile.am
  simulation/g4simulation/g4jets/Makefile.am
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#621 Fix lib deps
  offline/packages/mvtx/Makefile.am
  offline/packages/tpc/Makefile.am
  offline/packages/trackbase/Makefile.am
  simulation/g4simulation/g4intt/Makefile.am
  simulation/g4simulation/g4mvtx/Makefile.am
  simulation/g4simulation/g4tpc/Makefile.am
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#622 Evaluator containers
  offline/packages/trackbase/TrkrClusterHitAssoc.cc
  simulation/g4simulation/g4eval/Makefile.am
  simulation/g4simulation/g4eval/SvtxClusterEval.cc
  simulation/g4simulation/g4eval/SvtxClusterEval.h
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4eval/SvtxHitEval.cc
  simulation/g4simulation/g4eval/SvtxHitEval.h
  simulation/g4simulation/g4eval/SvtxTrackEval.cc
  simulation/g4simulation/g4eval/SvtxTrackEval.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#623 Fix makefiles
  offline/framework/frog/Makefile.am
  offline/framework/fun4all/Makefile.am
  offline/framework/phool/Makefile.am
  offline/framework/phool/PHRawDataNode.cc
  offline/framework/phool/PHRawDataNode.h
  offline/packages/NodeDump/Makefile.am
  offline/packages/PHGeometry/Makefile.am
  offline/packages/intt/Makefile.am
  offline/packages/jetbackground/Makefile.am
  offline/packages/mvtx/Makefile.am
  offline/packages/trigger/Makefile.am
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#626 Create maps layers in a unique subsystem module...
  simulation/g4simulation/g4mvtx/Makefile.am
  simulation/g4simulation/g4mvtx/PHG4MVTXDefs.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDefsLinkDef.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDetector.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDetector.h
  simulation/g4simulation/g4mvtx/PHG4MVTXSteppingAction.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXSubsystem.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#624 TrkrHitSetContainer::Reset() did not properly free memory allocated t…
  offline/packages/trackbase/TrkrHitSet.cc
  offline/packages/trackbase/TrkrHitSet.h
  offline/packages/trackbase/TrkrHitSetContainer.cc
  offline/packages/trackbase/TrkrHitSetContainer.h
  offline/packages/trackbase_historic/SvtxVertexMap.h
  offline/packages/trackbase_historic/SvtxVertexMap_v1.cc
  offline/packages/trackbase_historic/SvtxVertexMap_v1.h
  offline/packages/trackreco/PHGenFitTrkFitter.cc
  offline/packages/trackreco/PHHoughAllInOne.cc
  offline/packages/trackreco/PHHoughSeeding.cc
  offline/packages/trackreco/PHRaveVertexing.cc
  simulation/g4simulation/g4eval/SvtxClusterEval.cc
  simulation/g4simulation/g4eval/SvtxTrackEval.cc
  simulation/g4simulation/g4hough/PHG4HoughTransform.C
  simulation/g4simulation/g4hough/PHG4HoughTransformTPC.C
  simulation/g4simulation/g4hough/PHG4InitZVertexing.C
  simulation/g4simulation/g4hough/PHG4KalmanPatRec.C
  simulation/g4simulation/g4hough/PHG4PatternReco.C
  simulation/g4simulation/g4hough/PHG4TrackKalmanFitter.C
  simulation/g4simulation/g4hough/PHRaveVertexing.C
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#627 Fix some leaks
  offline/packages/HelixHough/helix_hough/HelixHough_init.cpp
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.h
  simulation/g4simulation/g4intt/INTTDeadMap.cc
  simulation/g4simulation/g4intt/INTTDeadMap.h
  simulation/g4simulation/g4intt/PHG4INTTHitReco.cc
  simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
  simulation/g4simulation/g4intt/PHG4InttDigitizer.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.h
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#625 Retire old container modules
  offline/packages/intt/INTTClusterizer.cc
  offline/packages/intt/INTTClusterizer.h
  offline/packages/intt/INTTClusterizerLinkDef.h
  offline/packages/intt/Makefile.am
  offline/packages/mvtx/MVTXClusterizer.cc
  offline/packages/mvtx/MVTXClusterizer.h
  offline/packages/mvtx/MVTXClusterizerLinkDef.h
  offline/packages/mvtx/Makefile.am
  offline/packages/tpc/Makefile.am
  offline/packages/tpc/TPCClusterizer.cc
  offline/packages/tpc/TPCClusterizer.h
  offline/packages/tpc/TPCClusterizerLinkDef.h
  simulation/g4simulation/g4dst/Makefile.am
  simulation/g4simulation/g4intt/Makefile.am
  simulation/g4simulation/g4intt/PHG4INTTCellReco.cc
  simulation/g4simulation/g4intt/PHG4INTTCellReco.h
  simulation/g4simulation/g4intt/PHG4INTTCellRecoLinkDef.h
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.cc
  simulation/g4simulation/g4intt/PHG4INTTDigitizer.h
  simulation/g4simulation/g4intt/PHG4INTTDigitizerLinkDef.h
  simulation/g4simulation/g4mvtx/Makefile.am
  simulation/g4simulation/g4mvtx/PHG4CylinderCell_MVTX.cc
  simulation/g4simulation/g4mvtx/PHG4CylinderCell_MVTX.h
  simulation/g4simulation/g4mvtx/PHG4CylinderCell_MVTXLinkDef.h
  simulation/g4simulation/g4mvtx/PHG4MVTXCellReco.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXCellReco.h
  simulation/g4simulation/g4mvtx/PHG4MVTXCellRecoLinkDef.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.cc
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizer.h
  simulation/g4simulation/g4mvtx/PHG4MVTXDigitizerLinkDef.h
  simulation/g4simulation/g4mvtx/PHG4MVTXHitReco.cc
  simulation/g4simulation/g4tpc/Makefile.am
  simulation/g4simulation/g4tpc/PHG4CellTPCv1.cc
  simulation/g4simulation/g4tpc/PHG4CellTPCv1.h
  simulation/g4simulation/g4tpc/PHG4CellTPCv1LinkDef.h
  simulation/g4simulation/g4tpc/PHG4TPCDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TPCDigitizer.h
  simulation/g4simulation/g4tpc/PHG4TPCDigitizerLinkDef.h
  simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TPCElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TPCElectronDriftLinkDef.h
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#628 More fixes
  offline/packages/trackreco/PHGenFitTrkProp.cc
  offline/packages/trackreco/PHGenFitTrkProp.h
  simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv2.h
  simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.cc
  simulation/g4simulation/g4detectors/PHG4CylinderGeom_Spacalv3.h
  simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc
  simulation/g4simulation/g4mvtx/Makefile.am
  simulation/g4simulation/g4mvtx/PHG4MVTXDetector.cc
  simulation/g4simulation/g4tpc/PHG4TPCPadPlaneReadout.cc
  simulation/g4simulation/g4tpc/PHG4TPCPadPlaneReadout.h
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
Labels: CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
