Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2020-11, with the labels that each got.

#972 Remove pai
  offline/framework/fun4all/Fun4AllDstOutputManager.cc
  offline/framework/fun4all/Fun4AllDstOutputManager.h
  offline/framework/fun4all/Fun4AllOutputManager.h
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4main/PHG4TruthEventAction.cc
Labels: CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-scan-PENDING, CI-cpp-check-PENDING

#973 Add finer verbosity statements
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#974 Removed output Ntuple from CA seeding
  offline/packages/trackreco/PHCASeeding.cc
Labels: CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-scan-PENDING, CI-cpp-check-PENDING

#975 Add theta to calogeo
  offline/packages/CaloBase/RawTower.h
  offline/packages/CaloBase/RawTowerGeomContainer.h
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.cc
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h
  simulation/g4simulation/g4histos/G4EdepNtuple.cc
  simulation/g4simulation/g4histos/G4HitNtuple.cc
  simulation/g4simulation/g4histos/G4HitTTree.cc
  simulation/g4simulation/g4histos/G4RawTowerTTree.cc
  simulation/g4simulation/g4histos/G4ScintillatorSlatTTree.cc
  simulation/g4simulation/g4histos/G4ScintillatorTowerTTree.cc
  simulation/g4simulation/g4histos/G4SnglNtuple.cc
  simulation/g4simulation/g4histos/G4SnglTree.cc
  simulation/g4simulation/g4histos/G4TowerNtuple.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#978 Cluster key look up
  offline/packages/trackreco/ActsEvaluator.cc
  offline/packages/trackreco/ActsEvaluator.h
  offline/packages/trackreco/ActsTransformations.cc
  offline/packages/trackreco/ActsTransformations.h
  offline/packages/trackreco/PHActsSourceLinks.cc
  offline/packages/trackreco/PHActsSourceLinks.h
  offline/packages/trackreco/PHActsTracks.cc
  offline/packages/trackreco/PHActsTracks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHActsTrkProp.cc
  offline/packages/trackreco/PHActsTrkProp.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#977 Tpc distortion correction
  offline/packages/tpc/Makefile.am
  offline/packages/tpc/TpcSpaceChargeCorrection.cc
  offline/packages/tpc/TpcSpaceChargeCorrection.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#979 Add PHTimer timers
  offline/packages/trackreco/PHActsSourceLinks.cc
  offline/packages/trackreco/PHActsTracks.cc
  offline/packages/trackreco/PHActsTracks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#976 Tpc distortion reconstruction
  offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
  offline/packages/tpccalib/TpcSpaceChargeReconstruction.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#980 Acts track-to-calo projection
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsTrackProjection.cc
  offline/packages/trackreco/PHActsTrackProjection.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#982 fix print formatting
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#984 flow afterburner: adjust parameters
  generators/flowAfterburner/flowAfterburner.cc
  generators/flowAfterburner/main.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#983 Protection against overlapping events
  simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#985 Pileup input manager
  simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc
  simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#987 Acts truth seeding
  offline/packages/trackreco/PHActsTracks.cc
  offline/packages/trackreco/PHActsTracks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHTruthTrackSeeding.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#986 Sync
  offline/framework/ffamodules/Makefile.am
  offline/framework/ffamodules/SyncReco.cc
  offline/framework/ffamodules/SyncReco.h
  offline/framework/ffamodules/autogen.sh
  offline/framework/ffamodules/configure.ac
  offline/framework/ffaobjects/Makefile.am
  offline/framework/fun4all/Fun4AllServer.cc
  offline/framework/fun4all/Fun4AllServer.h
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4ConeDetector.cc
  simulation/g4simulation/g4detectors/PHG4ConeDetector.h
  simulation/g4simulation/g4detectors/PHG4ConeDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4ConeDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4ConeRegionSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ConeRegionSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4ConeSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4ConeSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4ConeSubsystem.h
  simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc
  simulation/g4simulation/g4histos/G4SnglNtuple.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#988 Fix input managers
  offline/framework/ffamodules/SyncReco.cc
  offline/framework/ffamodules/SyncReco.h
  offline/framework/ffaobjects/SyncDefs.h
  offline/framework/fun4all/Fun4AllDstInputManager.cc
  offline/framework/fun4all/Fun4AllDummyInputManager.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#989 Fix memory leaks
  offline/packages/trackreco/MakeActsGeometry.cc
  offline/packages/trackreco/PHActsSourceLinks.cc
  offline/packages/trackreco/PHActsSourceLinks.h
  offline/packages/trackreco/PHActsTracks.cc
  offline/packages/trackreco/PHActsTrkFitter.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#990 Return calogeo theta
  offline/packages/CaloBase/RawTowerGeom.h
  offline/packages/CaloBase/RawTowerGeomContainer.h
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.cc
  offline/packages/CaloBase/RawTowerGeomContainer_Cylinderv1.h
  offline/packages/CaloBase/RawTowerGeomv1.cc
  offline/packages/CaloBase/RawTowerGeomv1.h
  offline/packages/CaloBase/RawTowerGeomv3.cc
  offline/packages/CaloBase/RawTowerGeomv3.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#991 sHijing cmdparser
  generators/sHijing/Hijing.cxx
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#992 Fix track state extrapolation along r. (dr/dt was improperly calculated)
  offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#994 Fix fermi flow
  generators/FermiMotionAfterburner/FermiMotion.cc
  generators/FermiMotionAfterburner/FermimotionAfterburner.cc
  generators/FermiMotionAfterburner/FermimotionAfterburner.h
  generators/FermiMotionAfterburner/configure.ac
  generators/flowAfterburner/flowAfterburner.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#993 Allow QA module to select a vertex map
  offline/QA/modules/QAG4SimulationVertex.cc
  offline/QA/modules/QAG4SimulationVertex.h
  offline/packages/trackreco/PHRaveVertexing.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#995 Acts vertexing
  offline/packages/trackreco/PHActsVertexFinder.cc
  offline/packages/trackreco/PHActsVertexFinder.h
  offline/packages/trackreco/PHActsVertexFitter.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#998 Small fixes
  offline/packages/CaloReco/BEmcRec.cc
  offline/packages/trackreco/MakeActsGeometry.cc
  simulation/g4simulation/g4histos/G4VtxNtuple.cc
  simulation/g4simulation/g4histos/G4VtxNtuple.h
  simulation/g4simulation/g4histos/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#997 Allow QA module to select a vertex map #993 try-2
  offline/QA/modules/QAG4SimulationVertex.cc
  offline/QA/modules/QAG4SimulationVertex.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#999 Add missing verbosity filter
  offline/packages/particleflow/ParticleFlowReco.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1000 [CA Seeding] Removed TNtuple and converted PHTimers to smart pointers
  offline/packages/trackreco/PHCASeeding.cc
  offline/packages/trackreco/PHCASeeding.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1002 Fermiupdate
  generators/FermiMotionAfterburner/FermiMotion.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1001 Tpc cluster mover
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsTracks.cc
  offline/packages/trackreco/PHCASeeding.cc
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
  offline/packages/trackreco/PHTpcClusterMover.cc
  offline/packages/trackreco/PHTpcClusterMover.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1003 fix remaining mem leaks in Acts and stub matching
  offline/packages/trackreco/PHActsSourceLinks.cc
  offline/packages/trackreco/PHActsVertexFinder.cc
  offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1004 Update SvtxVertex with track ids
  offline/packages/trackreco/PHActsVertexFinder.cc
  offline/packages/trackreco/PHActsVertexFinder.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1005 Add acts vertexing to SvtxEvaluator
  offline/packages/trackreco/PHActsVertexFinder.cc
  simulation/g4simulation/g4eval/SvtxEvalStack.h
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.h
  simulation/g4simulation/g4eval/SvtxVertexEval.cc
  simulation/g4simulation/g4eval/SvtxVertexEval.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1006 make all spectator neutrons the daughter of each original neutron, de…
  generators/FermiMotionAfterburner/FermiMotion.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1007 Cluster
  offline/packages/CaloReco/BEmcCluster.cc
  offline/packages/CaloReco/BEmcRec.h
  offline/packages/CaloReco/BEmcRecCEMC.cc
  offline/packages/CaloReco/BEmcRecCEMC.h
  offline/packages/CaloReco/BEmcRecEEMC.cc
  offline/packages/CaloReco/BEmcRecEEMC.h
  offline/packages/CaloReco/BEmcRecFEMC.cc
  offline/packages/CaloReco/BEmcRecFEMC.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#1008 Headreco
  generators/FermiMotionAfterburner/FermiMotion.cc
  generators/flowAfterburner/flowAfterburner.cc
  generators/flowAfterburner/flowAfterburner.h
  offline/framework/ffamodules/HeadReco.cc
  offline/framework/ffamodules/HeadReco.h
  offline/framework/ffamodules/Makefile.am
  offline/framework/ffaobjects/EventHeader.cc
  offline/framework/ffaobjects/EventHeader.h
  offline/framework/ffaobjects/EventHeaderLinkDef.h
  offline/framework/ffaobjects/EventHeaderv1.cc
  offline/framework/ffaobjects/EventHeaderv1.h
  offline/framework/ffaobjects/EventHeaderv1LinkDef.h
  offline/framework/ffaobjects/EventHeaderv2.cc
  offline/framework/ffaobjects/EventHeaderv2.h
  offline/framework/ffaobjects/EventHeaderv2LinkDef.h
  offline/framework/ffaobjects/FlagSave.h
  offline/framework/ffaobjects/FlagSaveLinkDef.h
  offline/framework/ffaobjects/FlagSavev1.cc
  offline/framework/ffaobjects/FlagSavev1.h
  offline/framework/ffaobjects/FlagSavev1LinkDef.h
  offline/framework/ffaobjects/Makefile.am
  offline/framework/ffaobjects/RunHeader.cc
  offline/framework/ffaobjects/RunHeader.h
  offline/framework/ffaobjects/RunHeaderLinkDef.h
  offline/framework/ffaobjects/RunHeaderv1.cc
  offline/framework/ffaobjects/RunHeaderv1.h
  offline/framework/ffaobjects/RunHeaderv1LinkDef.h
  offline/framework/ffaobjects/SyncDefs.h
  offline/framework/ffaobjects/SyncObject.cc
  offline/framework/ffaobjects/SyncObject.h
  offline/framework/ffaobjects/SyncObjectLinkDef.h
  offline/framework/ffaobjects/SyncObjectv1.cc
  offline/framework/ffaobjects/SyncObjectv1.h
  offline/framework/ffaobjects/SyncObjectv1LinkDef.h
  offline/packages/NodeDump/DumpEventHeader.cc
  offline/packages/NodeDump/DumpEventHeader.h
  offline/packages/NodeDump/DumpRunHeader.cc
  offline/packages/NodeDump/DumpRunHeader.h
  offline/packages/NodeDump/Dumper.cc
  offline/packages/NodeDump/Makefile.am
  offline/packages/NodeDump/PHNodeDump.cc
  offline/packages/PHField/PHField2D.cc
  offline/packages/PHField/PHFieldBeast.h
  offline/packages/PHField/PHFieldCleo.cc
  offline/packages/PHField/PHFieldConfigv1.cc
  offline/packages/PHField/PHFieldConfigv2.cc
  offline/packages/PHField/PHFieldUtility.cc
  simulation/g4simulation/g4detectors/PHG4HcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4HcalSteppingAction.h
  simulation/g4simulation/g4histos/G4CellNtuple.cc
  simulation/g4simulation/g4histos/G4VtxNtuple.cc
  simulation/g4simulation/g4histos/G4VtxNtuple.h
  simulation/g4simulation/g4main/Fun4AllDstPileupInputManager.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1010 Fix fermi
  generators/FermiMotionAfterburner/FermiMotion.cc
  generators/phhepmc/PHHepMC_ioLinkDef.h
  offline/framework/ffamodules/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
