Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2020-03, with the labels that each got.

#751 Stacktrace
  offline/database/PHParameter/PHParameterContainerInterface.cc
  offline/database/PHParameter/PHParameterContainerInterface.h
  offline/database/PHParameter/PHParameterContainerInterfaceLinkDef.h
  offline/database/PHParameter/PHParameterInterface.cc
  offline/database/PHParameter/PHParameterInterface.h
  offline/database/PHParameter/PHParameterInterfaceLinkDef.h
  offline/database/PHParameter/PHParameters.cc
  offline/database/PHParameter/PHParameters.h
  offline/database/PHParameter/PHParametersContainer.cc
  offline/database/PHParameter/PHParametersContainer.h
  offline/database/PHParameter/PHParametersContainerLinkDef.h
  offline/database/PHParameter/PHParametersLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#752 Prepare Track Fitting
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHGenFitTrkProp.cc
  offline/packages/trackreco/TrkrClusterSourceLink.hpp
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#754 Display genfit
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#755 Fix cellreco
  simulation/g4simulation/g4detectors/PHG4Cell.h
  simulation/g4simulation/g4detectors/PHG4CellDefs.cc
  simulation/g4simulation/g4detectors/PHG4Cellv1.cc
  simulation/g4simulation/g4detectors/PHG4Cellv1.h
  simulation/g4simulation/g4detectors/PHG4CylinderCellReco.cc
  simulation/g4simulation/g4histos/G4CellNtuple.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#756 Cluster efficiency
  offline/packages/tpc/TpcClusterizer.cc
  offline/packages/tpc/TpcClusterizer.h
  offline/packages/trackreco/PHGenFitTrkFitter.cc
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#758 Removed obsolete classes:
  offline/packages/NodeDump/DumpSvtxClusterMap.cc
  offline/packages/NodeDump/DumpSvtxClusterMap.h
  offline/packages/NodeDump/DumpSvtxHitMap.cc
  offline/packages/NodeDump/DumpSvtxHitMap.h
  offline/packages/NodeDump/Makefile.am
  offline/packages/NodeDump/PHNodeDump.cc
  offline/packages/trackbase/Makefile.am
  offline/packages/trackbase/TrkrHitCellAssoc.cc
  offline/packages/trackbase/TrkrHitCellAssoc.h
  offline/packages/trackbase/TrkrHitCellAssocLinkDef.h
  offline/packages/trackbase_historic/Makefile.am
  offline/packages/trackbase_historic/SvtxCluster.h
  offline/packages/trackbase_historic/SvtxClusterLinkDef.h
  offline/packages/trackbase_historic/SvtxClusterMap.h
  offline/packages/trackbase_historic/SvtxClusterMapLinkDef.h
  offline/packages/trackbase_historic/SvtxClusterMap_v1.cc
  offline/packages/trackbase_historic/SvtxClusterMap_v1.h
  offline/packages/trackbase_historic/SvtxClusterMap_v1LinkDef.h
  offline/packages/trackbase_historic/SvtxCluster_v1.cc
  offline/packages/trackbase_historic/SvtxCluster_v1.h
  offline/packages/trackbase_historic/SvtxCluster_v1LinkDef.h
  offline/packages/trackbase_historic/SvtxHit.h
  offline/packages/trackbase_historic/SvtxHitLinkDef.h
  offline/packages/trackbase_historic/SvtxHitMap.h
  offline/packages/trackbase_historic/SvtxHitMapLinkDef.h
  offline/packages/trackbase_historic/SvtxHitMap_v1.cc
  offline/packages/trackbase_historic/SvtxHitMap_v1.h
  offline/packages/trackbase_historic/SvtxHitMap_v1LinkDef.h
  offline/packages/trackbase_historic/SvtxHit_v1.cc
  offline/packages/trackbase_historic/SvtxHit_v1.h
  offline/packages/trackbase_historic/SvtxHit_v1LinkDef.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#759 Acts Track Fitting
  offline/packages/trackreco/ActsFittingAlgorithm.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/TrkrClusterSourceLink.hpp
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-FAIL, CI-build-x8664_sl7-root5-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#760 Trigger a tracking QA check
  simulation/g4simulation/g4decayer/configure.ac
  simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc
  simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#761 Cluster eval fix
  simulation/g4simulation/g4eval/BaseTruthEval.cc
  simulation/g4simulation/g4eval/Makefile.am
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4eval/SvtxHitEval.cc
  simulation/g4simulation/g4eval/SvtxTrackEval.cc
  simulation/g4simulation/g4eval/SvtxVertexEval.cc
  simulation/g4simulation/g4eval/TrkrEvaluator.cc
  simulation/g4simulation/g4eval/TrkrEvaluator.h
  simulation/g4simulation/g4eval/TrkrEvaluatorLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#762 Adding configurable topoCluster splitting capability
  offline/packages/CaloReco/RawClusterBuilderTopo.cc
  offline/packages/CaloReco/RawClusterBuilderTopo.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#763 Fixing memory hosted eval NTuple in TPC digitization
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#705 Simulating TPC GEM gain fluctuation
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-gcc-8.3-new-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#764 Acts Fitting Modularization
  offline/packages/trackreco/ActsFittingAlgorithm.h
  offline/packages/trackreco/MakeActsGeometry.cc
  offline/packages/trackreco/MakeActsGeometry.h
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsSourceLinks.cc
  offline/packages/trackreco/PHActsSourceLinks.h
  offline/packages/trackreco/PHActsTracks.cc
  offline/packages/trackreco/PHActsTracks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/TrkrClusterSourceLink.hpp
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#765 Upstream/master error api
  offline/packages/trackbase/TrkrClusterv1.cc
  offline/packages/trackbase/TrkrClusterv1.h
  offline/packages/trackbase_historic/SvtxTrackState.h
  offline/packages/trackbase_historic/SvtxTrackState_v1.cc
  offline/packages/trackbase_historic/SvtxTrackState_v1.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-root5-PENDING, CI-build-x8664_sl7-scan-PENDING, CI-calo-QA-PENDING, CI-cpp-check-PENDING, CI-track-low-occ-QA-PENDING, CI-valgrind-PENDING

#766 bugfix in TopoCluster code
  offline/packages/CaloReco/RawClusterBuilderTopo.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#768 Upstream/master spacechargereconstruction
  offline/packages/tpccalib/Makefile.am
  offline/packages/tpccalib/TpcSpaceChargeReconstruction.cc
  offline/packages/tpccalib/TpcSpaceChargeReconstruction.h
  offline/packages/tpccalib/TpcSpaceChargeReconstructionLinkDef.h
  offline/packages/tpccalib/autogen.sh
  offline/packages/tpccalib/configure.ac
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-root5-PENDING, CI-build-x8664_sl7-scan-PENDING, CI-calo-QA-PENDING, CI-cpp-check-PENDING, CI-track-low-occ-QA-PENDING, CI-valgrind-PENDING
