Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2020-02, with the labels that each got.

#741 Acts implementation
  offline/packages/intt/CylinderGeomIntt.cc
  offline/packages/intt/CylinderGeomIntt.h
  offline/packages/intt/InttClusterizer.cc
  offline/packages/mvtx/CylinderGeom_Mvtx.cc
  offline/packages/mvtx/CylinderGeom_Mvtx.h
  offline/packages/mvtx/MvtxClusterizer.cc
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHTrackFitting.h
  offline/packages/trackreco/configure.ac
  simulation/g4simulation/g4intt/PHG4InttSteppingAction.cc
  simulation/g4simulation/g4intt/PHG4InttSubsystem.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#742 Add EMCal layer in 3-D topoClustering
  offline/packages/CaloReco/RawClusterBuilderTopo.cc
  offline/packages/CaloReco/RawClusterBuilderTopo.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#743 Fix nullptr check
  offline/packages/trackreco/PHActsTrkFitter.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#745 added momentum information to g4hits
  simulation/g4simulation/g4tpc/PHG4TpcSteppingAction.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#747 fix compilation error, exit() if layer is not found, fix up includes
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-PENDING

#744 Upstream/master genfit trk fitter disable layers
  offline/packages/trackreco/PHGenFitTrkFitter.cc
  offline/packages/trackreco/PHGenFitTrkFitter.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#748 Fixed cppcheck warnings, cleaned a few things up
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#746 Clusterizer
  offline/packages/CaloReco/BEmcCluster.cc
  offline/packages/CaloReco/BEmcProfile.cc
  offline/packages/CaloReco/BEmcRec.cc
  offline/packages/CaloReco/BEmcRec.h
  offline/packages/CaloReco/BEmcRecCEMC.cc
  offline/packages/CaloReco/BEmcRecCEMC.h
  offline/packages/CaloReco/BEmcRecEEMC.cc
  offline/packages/CaloReco/BEmcRecEEMC.h
  offline/packages/CaloReco/BEmcRecFEMC.cc
  offline/packages/CaloReco/BEmcRecFEMC.h
  offline/packages/CaloReco/RawClusterBuilderTemplate.cc
  offline/packages/CaloReco/RawClusterBuilderTemplate.h
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#749 Master optimize tpc electron drift
  offline/packages/trackbase/TrkrHitSetContainer.cc
  offline/packages/trackbase/TrkrHitTruthAssoc.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
