Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2020-12, with the labels that each got.

#1011 Acts Vertex Finder Memory
  offline/packages/trackreco/PHActsVertexFinder.cc
  offline/packages/trackreco/PHActsVertexFinder.h
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-FAIL

#1012 remove check on unused truth info container
  offline/packages/trackreco/PHRaveVertexing.cc
  offline/packages/trackreco/PHRaveVertexing.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1013 modify for sPhenix dcache
  offline/framework/frog/FROG.cc
  offline/framework/frog/FROG.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1014 Project tracks with CEMC position recalibrated clusters
  offline/packages/trackreco/PHActsTrackProjection.cc
  offline/packages/trackreco/PHActsTrackProjection.h
  offline/packages/trackreco/PHGenFitTrackProjection.cc
  offline/packages/trackreco/PHGenFitTrackProjection.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1015 Crystal phparameter
  offline/packages/NodeDump/macro/run_dump.C
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-PENDING, CI-valgrind-PENDING

#1009 Master hklest
  simulation/g4simulation/g4tpc/DistortedTrackContainer.cc
  simulation/g4simulation/g4tpc/DistortedTrackContainer.h
  simulation/g4simulation/g4tpc/DistortedTrackContainerLinkDef.h
  simulation/g4simulation/g4tpc/DistortionStruct.h
  simulation/g4simulation/g4tpc/Makefile.am
  simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc
  simulation/g4simulation/g4tpc/PHG4TpcDistortion.h
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TpcSpaceChargeDistortion.cc
  simulation/g4simulation/g4tpc/PHG4TpcSpaceChargeDistortion.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1016 Acts silicon seeding
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsSiliconSeeding.cc
  offline/packages/trackreco/PHActsSiliconSeeding.h
Labels: CI-DST-readback-FAIL, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE, CI-valgrind-FAIL

#1017 Added missing include
  simulation/g4simulation/g4tpc/PHG4TpcDistortion.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1018 More crytalcalo params
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1019 Branchwarning
  offline/framework/fun4all/Fun4AllDstInputManager.cc
  offline/framework/fun4all/Fun4AllInputManager.h
  offline/framework/phool/PHNodeIOManager.cc
  offline/framework/phool/PHNodeIOManager.h
  offline/framework/phool/PHTimer.cc
  offline/framework/phool/PHTimer.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1020 Initial vertexing
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsInitialVertexFinder.cc
  offline/packages/trackreco/PHActsInitialVertexFinder.h
  offline/packages/trackreco/PHActsSiliconSeeding.cc
  offline/packages/trackreco/PHActsSiliconSeeding.h
  offline/packages/trackreco/PHActsVertexFinder.cc
  offline/packages/trackreco/PHActsVertexFinder.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1021 More crystal calo
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDefs.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterSubsystem.h
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.cc
  simulation/g4simulation/g4detectors/PHG4ProjCrystalCalorimeterDetector.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1022 Mdc1 fixes
  offline/framework/frog/FROG.cc
  offline/framework/frog/FROG.h
  offline/framework/fun4all/Fun4AllServer.cc
  offline/framework/phool/Makefile.am
  offline/framework/phool/PHIOManager.cc
  offline/framework/phool/PHIOManager.h
  offline/framework/phool/PHNodeIOManager.cc
  offline/framework/phool/PHNodeIOManager.h
  simulation/g4simulation/g4dst/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1023 Switch Seeding to MVTX
  offline/packages/trackreco/PHActsSiliconSeeding.cc
  offline/packages/trackreco/PHActsSiliconSeeding.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1024 Sync fix
  offline/framework/fun4all/Fun4AllDstInputManager.cc
  offline/framework/fun4all/Fun4AllDstInputManager.h
  offline/framework/fun4all/Fun4AllInputManager.h
  offline/framework/fun4all/Fun4AllNoSyncDstInputManager.h
  offline/framework/fun4all/Fun4AllSyncManager.cc
  offline/framework/fun4all/Fun4AllSyncManager.h
  offline/framework/fun4allraw/Fun4AllPrdfInputManager.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1026 fix sync object read for filelists
  offline/framework/fun4all/Fun4AllDstInputManager.cc
  offline/framework/fun4all/Fun4AllSyncManager.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1028 Intt projection update
  offline/packages/trackreco/PHActsSiliconSeeding.cc
  offline/packages/trackreco/PHActsSiliconSeeding.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1027 Use proper interface when access data
  simulation/g4simulation/g4eval/PHG4DSTReader.cc
  simulation/g4simulation/g4main/PHG4Showerv1.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1030 Fix silicon seed PCA requirement
  offline/packages/trackreco/PHActsInitialVertexFinder.cc
  offline/packages/trackreco/PHActsSiliconSeeding.cc
  offline/packages/trackreco/PHActsSiliconSeeding.h
  offline/packages/trackreco/PHActsTrkFitter.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1031 Get filelist
  offline/framework/frog/CreateFileList.pl
  offline/framework/frog/Makefile.am
Labels: CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-scan-PENDING, CI-cpp-check-PENDING

#1033 Z vertex fitter
  offline/packages/trackreco/PHActsSiliconSeeding.h
  offline/packages/trackreco/PHActsVertexFitter.cc
  offline/packages/trackreco/PHActsVertexFitter.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1032 KFParticle
  offline/packages/CaloBase/Makefile.am
  offline/packages/KFParticle_sPHENIX/KFParticle_Container.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_Container.h
  offline/packages/KFParticle_sPHENIX/KFParticle_ContainerLinkDef.h
  offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_DST.h
  offline/packages/KFParticle_sPHENIX/KFParticle_MVA.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_MVA.h
  offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
  offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.h
  offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
  offline/packages/KFParticle_sPHENIX/KFParticle_particleList.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_particleList.h
  offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
  offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h
  offline/packages/KFParticle_sPHENIX/Makefile.am
  offline/packages/KFParticle_sPHENIX/autogen.sh
  offline/packages/KFParticle_sPHENIX/configure.ac
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, preview-do-not-merge

#1035 Pythia Trigger update in preparation for MDC HF production jobs
  generators/PHPythia8/PHPy8ParticleTrigger.cc
  generators/PHPythia8/PHPy8ParticleTrigger.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1036 Minor change to KFParticle
  offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_particleList.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1037 Fix class message
  offline/packages/KFParticle_sPHENIX/Makefile.am
  simulation/g4simulation/g4detectors/PHG4CrystalCalorimeterDetector.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1039 Electron drift speedup
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#1040 need to use LIBADD when libs dependency affects build order
  offline/packages/KFParticle_sPHENIX/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
