Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2020-10, with the labels that each got.

#937 Delete tmp file
  generators/PHPythia6/Makefile.am
  generators/PHPythia6/PHPy6ForwardElectronTrig.h
  generators/PHPythia6/PHPy6ForwardElectronTrigLinkDef.h
  generators/PHPythia6/PHPy6GenTrigger.cc
  generators/PHPythia6/PHPy6GenTrigger.h
  generators/PHPythia6/PHPy6GenTriggerLinkDef.h
  generators/PHPythia6/PHPy6JetTrigger.cc
  generators/PHPythia6/PHPy6JetTrigger.h
  generators/PHPythia6/PHPy6JetTriggerLinkDef.h
  generators/PHPythia6/PHPy6ParticleTrigger.cc
  generators/PHPythia6/PHPy6ParticleTrigger.h
  generators/PHPythia6/PHPy6ParticleTriggerLinkDef.h
  generators/PHPythia6/PHPythia6.cc
  generators/PHPythia6/PHPythia6LinkDef.h
  generators/PHPythia6/configure.ac
  generators/PHPythia8/Makefile.am
  generators/PHPythia8/PHPy8GenTriggerLinkDef.h
  generators/PHPythia8/PHPy8JetTriggerLinkDef.h
  generators/PHPythia8/PHPy8ParticleTriggerLinkDef.h
  generators/PHPythia8/PHPythia8LinkDef.h
  generators/PHPythia8/configure.ac
  generators/PHSartre/Makefile.am
  generators/PHSartre/PHSartreGenTriggerLinkDef.h
  generators/PHSartre/PHSartreLinkDef.h
  generators/PHSartre/PHSartreParticleTriggerLinkDef.h
  generators/PHSartre/configure.ac
  generators/phhepmc/Fun4AllHepMCInputManager.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#938 aded missing "continue" statement
  offline/packages/trackreco/PHGenFitTrkFitter.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-FAIL, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-FAIL, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#939 Add lib64
  offline/framework/fun4all/CreateSubsysRecoModule.pl
  simulation/g4simulation/g4detectors/CreateG4Subsystem.pl
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4EnvelopeSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4mRICHSteppingAction.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#940 CA Seeding update
  offline/packages/trackreco/PHCASeeding.cc
  offline/packages/trackreco/PHCASeeding.h
  offline/packages/trackreco/PHTrackSeeding.cc
  offline/packages/trackreco/PHTrackSeeding.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-FAIL, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#944 Configure PFlow matching criteria and emulate finite track efficiency
  offline/packages/particleflow/ParticleFlowReco.cc
  offline/packages/particleflow/ParticleFlowReco.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-FAIL, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#942 Fix cppcheck
  offline/packages/trackreco/ActsTrack.h
  offline/packages/trackreco/CellularAutomaton_v1.cc
  offline/packages/trackreco/CellularAutomaton_v1.h
  offline/packages/trackreco/GPUTPCTrackParamLinkDef.h
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PH3DVertexingLinkDef.h
  offline/packages/trackreco/PHActsSourceLinks.h
  offline/packages/trackreco/PHCASeeding.h
  offline/packages/trackreco/PHCASeedingLinkDef.h
  offline/packages/trackreco/PHGenFitTrackProjection.cc
  offline/packages/trackreco/PHGenFitTrackProjectionLinkDef.h
  offline/packages/trackreco/PHGenFitTrkFitter.h
  offline/packages/trackreco/PHGenFitTrkFitterLinkDef.h
  offline/packages/trackreco/PHGenFitTrkPropLinkDef.h
  offline/packages/trackreco/PHHoughSeeding.cc
  offline/packages/trackreco/PHHoughSeeding.h
  offline/packages/trackreco/PHHoughSeedingLinkDef.h
  offline/packages/trackreco/PHInitVertexingLinkDef.h
  offline/packages/trackreco/PHInitZVertexing.h
  offline/packages/trackreco/PHInitZVertexingLinkDef.h
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
  offline/packages/trackreco/PHMicromegasTpcTrackMatchingLinkDef.h
  offline/packages/trackreco/PHPatternReco.h
  offline/packages/trackreco/PHPatternRecoLinkDef.h
  offline/packages/trackreco/PHRTreeSeeding.cc
  offline/packages/trackreco/PHRTreeSeeding.h
  offline/packages/trackreco/PHRTreeSeedingLinkDef.h
  offline/packages/trackreco/PHRaveVertexingLinkDef.h
  offline/packages/trackreco/PHSiliconTpcTrackMatching.h
  offline/packages/trackreco/PHSiliconTpcTrackMatchingLinkDef.h
  offline/packages/trackreco/PHSiliconTruthTrackSeedingLinkDef.h
  offline/packages/trackreco/PHTrackFittingLinkDef.h
  offline/packages/trackreco/PHTrackPropagatingLinkDef.h
  offline/packages/trackreco/PHTrackSeedingLinkDef.h
  offline/packages/trackreco/PHTrackSetMerging.cc
  offline/packages/trackreco/PHTrackSetMerging.h
  offline/packages/trackreco/PHTrackSetMergingLinkDef.h
  offline/packages/trackreco/PHTruthTrackSeeding.cc
  offline/packages/trackreco/PHTruthTrackSeedingLinkDef.h
  offline/packages/trackreco/PHTruthVertexing.h
  offline/packages/trackreco/PHTruthVertexingLinkDef.h
  offline/packages/trackreco/configure.ac
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#945 Fix ca seeding charge
  offline/packages/trackreco/PHCASeeding.cc
  offline/packages/trackreco/PHCASeeding.h
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
  offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
  offline/packages/trackreco/PHSiliconTpcTrackMatching.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-FAIL, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#946 Acts Tracking Geometry
  offline/packages/trackreco/ActsEvaluator.h
  offline/packages/trackreco/ActsTrack.h
  offline/packages/trackreco/ActsTrackingGeometry.h
  offline/packages/trackreco/MakeActsGeometry.cc
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsSourceLinks.h
  offline/packages/trackreco/PHActsTracks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHActsTrkProp.h
  offline/packages/trackreco/PHActsVertexFinder.h
  offline/packages/trackreco/PHActsVertexFitter.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#947 Remove root5 g4histos
  offline/framework/fun4allraw/Fun4AllEventOutStream.h
  offline/framework/fun4allraw/Fun4AllPrdfInputManagerLinkDef.h
  offline/framework/fun4allraw/Fun4AllPrdfOutputManagerLinkDef.h
  offline/framework/fun4allraw/Makefile.am
  offline/framework/fun4allraw/configure.ac
  simulation/g4simulation/g4histos/G4CellNtupleLinkDef.h
  simulation/g4simulation/g4histos/G4EdepNtupleLinkDef.h
  simulation/g4simulation/g4histos/G4HitNtupleLinkDef.h
  simulation/g4simulation/g4histos/G4HitTTreeLinkDef.h
  simulation/g4simulation/g4histos/G4RawTowerTTreeLinkDef.h
  simulation/g4simulation/g4histos/G4ScintillatorSlatTTreeLinkDef.h
  simulation/g4simulation/g4histos/G4ScintillatorTowerTTreeLinkDef.h
  simulation/g4simulation/g4histos/G4SnglNtupleLinkDef.h
  simulation/g4simulation/g4histos/G4SnglTreeLinkDef.h
  simulation/g4simulation/g4histos/G4TowerNtupleLinkDef.h
  simulation/g4simulation/g4histos/Makefile.am
Labels: CI-DST-readback-FAIL, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-FAIL, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-FAIL, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-FAIL, CI-track-low-occ-QA-FAIL, CI-valgrind-FAIL

#948 Fit Silicon + MMs
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#949 Standalone acts geometry
  offline/packages/trackreco/ActsSurfaceMaps.h
  offline/packages/trackreco/MakeActsGeometry.cc
  offline/packages/trackreco/MakeActsGeometry.h
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsSourceLinks.cc
  offline/packages/trackreco/PHActsSourceLinks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
Labels: CI-DST-readback-FAIL, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#950 Fix gcc 8.3
  offline/database/pdbcal/pg/configure.ac
  offline/framework/frog/configure.ac
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h
  simulation/g4simulation/g4tpc/PHG4TpcDistortion.h
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlane.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
Labels: CI-DST-readback-FAIL, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#952 g4epd: add scintillator light yields to epd hits
  simulation/g4simulation/g4epd/PHG4EPSteppingAction.cc
Labels: CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#951 Fermi motion afterburner
  generators/FermiMotionAfterburner/FermiMotion.cc
  generators/FermiMotionAfterburner/FermiMotion.h
  generators/FermiMotionAfterburner/FermimotionAfterburner.cc
  generators/FermiMotionAfterburner/FermimotionAfterburner.h
  generators/FermiMotionAfterburner/Makefile.am
  generators/FermiMotionAfterburner/autogen.sh
  generators/FermiMotionAfterburner/configure.ac
Labels: CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#954 Add bad track seed diagnostic
  offline/packages/trackreco/PHActsTracks.cc
Labels: CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#953 Initial Commit of MBD/BBC Subsystem
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
  simulation/g4simulation/g4detectors/PHG4BbcDetector.h
  simulation/g4simulation/g4detectors/PHG4BbcSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4BbcSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4BbcSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4BbcSubsystem.h
  simulation/g4simulation/g4detectors/PHG4BbcSubsystemLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#956 MBD/BBC added to macros in common and detectors, added parts of BBC housing
  simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
  simulation/g4simulation/g4detectors/PHG4BbcSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4BbcSubsystem.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#957 add EMCAL_TOPO as a possible input to jet finding
  simulation/g4simulation/g4jets/ClusterJetInput.cc
  simulation/g4simulation/g4jets/FastJetAlgo.cc
  simulation/g4simulation/g4jets/Jet.h
  simulation/g4simulation/g4jets/TowerJetInput.cc
  simulation/g4simulation/g4jets/TowerJetInput.h
  simulation/g4simulation/g4jets/TrackJetInput.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#958 Fix multiple vertex handling
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.h
  offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
  offline/packages/trackreco/PHSiliconTpcTrackMatching.h
  offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc
  offline/packages/trackreco/PHTrackFitting.h
  offline/packages/trackreco/PHTruthVertexing.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#959 Characterize particle flow elements by assumed particle type
  offline/packages/particleflow/ParticleFlowElement.h
  offline/packages/particleflow/ParticleFlowElementv1.cc
  offline/packages/particleflow/ParticleFlowElementv1.h
  offline/packages/particleflow/ParticleFlowReco.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#961 Secondary track vertex association
  offline/packages/trackreco/PHSiliconTruthTrackSeeding.cc
  offline/packages/trackreco/PHTruthVertexing.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#962 Crystal calo
  simulation/g4simulation/g4calo/RawTowerBuilderByHitIndex.cc
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4IonGun.cc
  simulation/g4simulation/g4main/PHG4IonGun.h
  simulation/g4simulation/g4main/PHG4ParticleGenerator.cc
  simulation/g4simulation/g4main/PHG4ParticleGenerator.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.cc
  simulation/g4simulation/g4main/PHG4ParticleGeneratorBase.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.cc
  simulation/g4simulation/g4main/PHG4ParticleGeneratorD0.h
  simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.cc
  simulation/g4simulation/g4main/PHG4ParticleGeneratorVectorMeson.h
  simulation/g4simulation/g4main/PHG4ParticleGun.cc
  simulation/g4simulation/g4main/PHG4ParticleGun.h
  simulation/g4simulation/g4main/PHG4PileupGenerator.cc
  simulation/g4simulation/g4main/PHG4PileupGenerator.h
  simulation/g4simulation/g4main/PHG4SimpleEventGenerator.cc
  simulation/g4simulation/g4main/PHG4SimpleEventGenerator.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#963 Distorted tracks
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.h
  offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
  offline/packages/trackreco/PHSiliconTpcTrackMatching.h
  simulation/g4simulation/g4tpc/DistortedTrackContainer.cc
  simulation/g4simulation/g4tpc/DistortedTrackContainer.h
  simulation/g4simulation/g4tpc/DistortedTrackContainerLinkDef.h
  simulation/g4simulation/g4tpc/DistortionStruct.h
  simulation/g4simulation/g4tpc/Makefile.am
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
  simulation/g4simulation/g4tpc/configure.ac
Labels: CI-DST-readback-FAIL, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE

#964 Add some timing verbosity statements
  offline/packages/trackreco/PHActsTrkFitter.cc
Labels: CI-DST-readback-FAIL, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-FAIL, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE

#965 Timer printout
  offline/framework/fun4all/Fun4AllMemoryTracker.cc
  offline/framework/fun4all/Fun4AllServer.cc
  offline/framework/phool/PHTimer.h
  offline/packages/particleflow/Makefile.am
  offline/packages/particleflow/ParticleFlowReco.cc
  offline/packages/particleflow/ParticleFlowReco.h
Labels: CI-DST-readback-FAIL, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE

#966 Add runnode select
  offline/framework/fun4all/Fun4AllDstInputManager.cc
  offline/framework/fun4all/Fun4AllDstOutputManager.cc
  offline/framework/fun4all/Fun4AllDstOutputManager.h
  offline/framework/fun4all/Fun4AllDummyInputManager.cc
  offline/framework/fun4all/Fun4AllDummyInputManager.h
  offline/framework/fun4all/Fun4AllInputManager.cc
  offline/framework/fun4all/Fun4AllInputManager.h
  offline/framework/fun4all/Fun4AllMemoryTracker.cc
  offline/framework/fun4all/Fun4AllNoSyncDstInputManager.h
  offline/framework/fun4all/Fun4AllOutputManager.h
  offline/framework/fun4all/Fun4AllReturnCodes.h
  offline/framework/fun4all/Fun4AllServer.cc
  offline/framework/fun4all/Fun4AllSyncManager.cc
  offline/framework/fun4all/Fun4AllUtils.cc
  offline/framework/fun4all/Fun4AllUtils.h
  offline/framework/fun4all/PHTFileServer.cc
  offline/framework/phool/PHNodeIterator.cc
  offline/framework/phoolraw/PHRawDataNode.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE

#967 Fix truth vertices
  offline/packages/trackreco/PHTruthVertexing.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE

#968 CA seeding NaN checking
  offline/packages/trackreco/PHCASeeding.cc
  offline/packages/trackreco/PHCASeeding.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-FAIL, CI-cpp-check-AVAILABLE

#969 Acts TPC Residuals
  offline/packages/trackreco/ActsTrack.h
  offline/packages/trackreco/MakeActsGeometry.cc
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHTpcResiduals.cc
  offline/packages/trackreco/PHTpcResiduals.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#970 evaluator verbosity update for performance checks
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE

#971 Fixing track seed charge issue
  offline/packages/trackreco/PHCASeeding.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-cpp-check-AVAILABLE
