Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2020-01, with the labels that each got.

#723 Adding RTree seeding
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHGenFitTrkProp.cc
  offline/packages/trackreco/PHRTreeSeeding.cc
  offline/packages/trackreco/PHRTreeSeeding.h
  offline/packages/trackreco/PHRTreeSeedingLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-FAIL, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#724 Fix root5
  offline/packages/trackreco/PHRTreeSeeding.cc
  offline/packages/trackreco/PHRTreeSeeding.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#725 Fix for gcc 8.3
  offline/packages/trackreco/PHRTreeSeeding.cc
  offline/packages/trackreco/configure.ac
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#726 next step towards iterative tracking
  offline/packages/trackreco/PHGenFitTrkFitter.h
  offline/packages/trackreco/PHInitZVertexing.cc
  offline/packages/trackreco/PHTrackFitting.cc
  offline/packages/trackreco/PHTrackPropagating.cc
  offline/packages/trackreco/PHTrackPropagating.h
  offline/packages/trackreco/PHTrackSeeding.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#728 add include to resolve phgenfit::Track
  offline/packages/trackreco/PHGenFitTrkFitter.h
Labels: CI-build-clang-PENDING, CI-build-new-PENDING, CI-build-root5-PENDING, CI-cpp-check-PENDING

#727 Changed definition of "iter" (dropped const modifier) to make it compile with clang 11
  offline/framework/fun4all/Fun4AllMemoryTracker.cc
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#729 root5 rootcint did not like the previous change, need to hide include
  offline/packages/trackreco/PHGenFitTrkFitter.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#730 properly set rnd seed in PHTruthVertexing
  offline/packages/trackreco/PHTruthVertexing.cc
  offline/packages/trackreco/PHTruthVertexing.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#732 Fix clone() call
  offline/framework/phool/PHNodeIntegrate.cc
  offline/framework/phool/PHObject.cc
Labels: CI-build-clang-PENDING, CI-build-new-PENDING, CI-build-root5-PENDING, CI-cpp-check-PENDING

#731 topoClusters as possible jet reco input
  simulation/g4simulation/g4jets/ClusterJetInput.cc
  simulation/g4simulation/g4jets/Jet.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#734 QA tracking
  offline/QA/modules/Makefile.am
  offline/QA/modules/QAG4SimulationTracking.cc
  offline/QA/modules/QAG4SimulationTracking.h
  offline/QA/modules/QAG4SimulationTrackingLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#736 Ycorrales new mvtx sim
  offline/packages/mvtx/CylinderGeom_Mvtx.cc
  offline/packages/mvtx/CylinderGeom_Mvtx.h
  offline/packages/mvtx/Makefile.am
  offline/packages/mvtx/MvtxClusterizer.cc
  offline/packages/mvtx/SegmentationAlpide.cc
  offline/packages/mvtx/SegmentationAlpide.h
  simulation/g4simulation/g4mvtx/PHG4MvtxDefs.h
  simulation/g4simulation/g4mvtx/PHG4MvtxDetector.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxDetector.h
  simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxSubsystem.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#738 Fix pixel out of range bug
  simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#737 Adding CA Seeding module
  offline/packages/trackreco/GPUTPCBaseTrackParam.h
  offline/packages/trackreco/GPUTPCTrackLinearisation.h
  offline/packages/trackreco/GPUTPCTrackParam.cxx
  offline/packages/trackreco/GPUTPCTrackParam.h
  offline/packages/trackreco/GPUTPCTrackParamLinkDef.h
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHCASeeding.cc
  offline/packages/trackreco/PHCASeeding.h
  offline/packages/trackreco/PHCASeedingLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#739 Changed track projection location for planar EM calorimeters
  simulation/g4simulation/g4eval/CaloEvaluator.cc
  simulation/g4simulation/g4eval/CaloEvaluator.h
  simulation/g4simulation/g4trackfastsim/PHG4TrackFastSim.cc
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE

#740 Placed first cell geometry inside conditional and set tower radius to…
  simulation/g4simulation/g4calo/RawTowerBuilder.cc
Labels: CI-DST-readback-PASS, CI-build-clang-PASS, CI-build-new-PASS, CI-build-root5-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE
