Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2020-04, with the labels that each got.

#770 Add tracker hit QA plots
  offline/QA/modules/QAG4SimulationTracking.cc
  offline/packages/trackbase_historic/SvtxTrack.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#771 Create module script
  offline/framework/fun4all/CreateSubsysRecoModule.pl
  offline/framework/fun4all/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#772 make printouts more visible, adding method to printout
  offline/framework/fun4all/CreateSubsysRecoModule.pl
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PENDING, CI-calo-QA-AVAILABLE, CI-cpp-check-PENDING, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-PENDING

#773 Fix g4hit
  simulation/g4simulation/g4detectors/CreateG4Subsystem.pl
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4main/PHG4Hit.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#774 Fix certain crash if !rf_track && !_over_write_svtxtrackmap
  offline/packages/trackreco/PHGenFitTrkFitter.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#775 the script now adds more comments to the sources
  simulation/g4simulation/g4detectors/CreateG4Subsystem.pl
Labels: CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-root5-PENDING, CI-build-x8664_sl7-scan-PENDING, CI-cpp-check-PENDING

#776 put more comments into source file
  offline/framework/fun4all/CreateSubsysRecoModule.pl
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PENDING, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-PENDING

#777 Acts track propagation
  offline/packages/trackreco/MakeActsGeometry.h
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsSourceLinks.cc
  offline/packages/trackreco/PHActsSourceLinks.h
  offline/packages/trackreco/PHActsTracks.cc
  offline/packages/trackreco/PHActsTracks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHActsTrkProp.cc
  offline/packages/trackreco/PHActsTrkProp.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#778 Track propagation
  offline/packages/trackreco/ActsTrack.h
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsTracks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHActsTrkProp.cc
  offline/packages/trackreco/PHActsTrkProp.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#779 Beast magnet
  offline/packages/PHField/Makefile.am
  offline/packages/PHField/PHField2D.cc
  offline/packages/PHField/PHField3DCartesian.cc
  offline/packages/PHField/PHField3DCylindrical.cc
  offline/packages/PHField/PHFieldBeast.cc
  offline/packages/PHField/PHFieldBeast.h
  offline/packages/PHField/PHFieldConfig.cc
  offline/packages/PHField/PHFieldConfig.h
  offline/packages/PHField/PHFieldConfigv1.cc
  offline/packages/PHField/PHFieldConfigv1.h
  offline/packages/PHField/PHFieldConfigv2.h
  offline/packages/PHField/PHFieldUniform.cc
  offline/packages/PHField/PHFieldUtility.cc
  simulation/g4simulation/g4gdml/Makefile.am
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4main/PHG4Reco.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#780 Default option to require unique matches for tracking efficiency QA
  offline/QA/modules/QAG4SimulationTracking.cc
  offline/QA/modules/QAG4SimulationTracking.h
  offline/QA/modules/QAG4SimulationUpsilon.cc
  offline/QA/modules/QAG4SimulationUpsilon.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#783 INTT G4 detector clean-up
  simulation/g4simulation/g4intt/PHG4InttDetector.cc
  simulation/g4simulation/g4intt/PHG4InttSubsystem.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#782 Add cleo
  offline/packages/PHField/Makefile.am
  offline/packages/PHField/PHFieldBeast.h
  offline/packages/PHField/PHFieldCleo.cc
  offline/packages/PHField/PHFieldCleo.h
  offline/packages/PHField/PHFieldConfig.cc
  offline/packages/PHField/PHFieldConfig.h
  offline/packages/PHField/PHFieldUtility.cc
  simulation/g4simulation/g4histos/G4HitNtuple.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#781 TPC in Acts
  offline/packages/trackreco/MakeActsGeometry.cc
  offline/packages/trackreco/MakeActsGeometry.h
  offline/packages/trackreco/PHActsSourceLinks.cc
  offline/packages/trackreco/PHActsSourceLinks.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHActsTrkProp.cc
  offline/packages/trackreco/PHActsTrkProp.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#784 Cleans up Geometry Creation
  offline/packages/trackreco/MakeActsGeometry.cc
  offline/packages/trackreco/MakeActsGeometry.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#785 check coordinates in outer loops during reading to avoid mishaps
  offline/packages/PHField/PHFieldCleo.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#786 Add beamline magnets
  simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc
  simulation/g4simulation/g4detectors/BeamLineMagnetDetector.h
  simulation/g4simulation/g4detectors/BeamLineMagnetDisplayAction.cc
  simulation/g4simulation/g4detectors/BeamLineMagnetDisplayAction.h
  simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.cc
  simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.h
  simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.cc
  simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.h
  simulation/g4simulation/g4detectors/BeamLineMagnetSubsystemLinkDef.h
  simulation/g4simulation/g4detectors/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-FAIL, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PENDING, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-PENDING, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#787 Upstream/master qa
  offline/QA/modules/Makefile.am
  offline/QA/modules/QAG4SimulationMvtx.cc
  offline/QA/modules/QAG4SimulationMvtx.h
  offline/QA/modules/QAG4SimulationMvtxLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#788 Clusterizer
  offline/packages/CaloReco/Makefile.am
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMC.h
  offline/packages/CaloReco/RawClusterBuilderTemplateEEMCLinkDef.h
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.cc
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMC.h
  offline/packages/CaloReco/RawClusterBuilderTemplateFEMCLinkDef.h
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#790 Few adjustment used in EIC beam pipe importing
  simulation/g4simulation/g4detectors/PHG4GDMLDetector.cc
  simulation/g4simulation/g4detectors/PHG4GDMLDetector.h
  simulation/g4simulation/g4detectors/PHG4GDMLSubsystem.cc
  simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.cc
  simulation/g4simulation/g4detectors/ePHENIXRICHConstruction.h
  simulation/g4simulation/g4main/PHG4Utils.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#791 Magnetic field default zero
  simulation/g4simulation/g4main/PHG4HitEval.cc
  simulation/g4simulation/g4main/PHG4HitEval.h
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4main/PHG4Utils.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-FAIL, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#792 reject HCal sub-cluster seeds that overlap with EMCal seed
  offline/packages/CaloReco/RawClusterBuilderTopo.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#793 Genfit lib64
  offline/packages/PHGenFitPkg/GenFitExp/Makefile.am
  offline/packages/PHGenFitPkg/PHGenFit/Fitter.cc
  offline/packages/PHGenFitPkg/PHGenFit/Makefile.am
  simulation/g4simulation/g4trackfastsim/Makefile.am
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE

#794 Changes for new Acts repository
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkProp.h
  offline/packages/trackreco/configure.ac
  simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxSteppingAction.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-PENDING, CI-build-x8664_sl7-clang-PASS, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-scan-PENDING, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-PENDING

#789 Evaluator truth clustering
  offline/framework/phool/PHRandomSeed.cc
  offline/packages/intt/CylinderGeomIntt.cc
  offline/packages/intt/CylinderGeomIntt.h
  offline/packages/mvtx/CylinderGeom_Mvtx.cc
  offline/packages/mvtx/MvtxClusterizer.cc
  offline/packages/mvtx/SegmentationAlpide.h
  offline/packages/tpc/TpcClusterizer.cc
  simulation/g4simulation/g4eval/Makefile.am
  simulation/g4simulation/g4eval/SvtxClusterEval.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.h
  test
  test2
Labels: CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-build-x8664_sl7-clang-PENDING, CI-build-x8664_sl7-new-PASS, CI-build-x8664_sl7-root5-FAIL, CI-build-x8664_sl7-scan-PASS, CI-calo-QA-AVAILABLE, CI-cpp-check-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-track-low-occ-QA-AVAILABLE, CI-valgrind-AVAILABLE
