Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2021-12, with the labels that each got.

#1351 check cluster existence before moving forward
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1350 added code to create new simplified materials for the TPC gems
  simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.cc
  simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
  simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h
  simulation/g4simulation/g4tpc/PHG4TpcDefs.h
  simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
  simulation/g4simulation/g4tpc/PHG4TpcDetector.h
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h
  simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
  simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.h
  simulation/g4simulation/g4tpc/PHG4TpcDisplayAction.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc
  simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.h
  simulation/g4simulation/g4tpc/PHG4TpcEndCapDisplayAction.cc
  simulation/g4simulation/g4tpc/PHG4TpcEndCapSteppingAction.cc
  simulation/g4simulation/g4tpc/PHG4TpcEndCapSteppingAction.h
  simulation/g4simulation/g4tpc/PHG4TpcEndCapSubsystem.cc
  simulation/g4simulation/g4tpc/PHG4TpcEndCapSubsystem.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlane.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlane.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneSimple.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneSimple.h
  simulation/g4simulation/g4tpc/PHG4TpcSteppingAction.cc
  simulation/g4simulation/g4tpc/PHG4TpcSteppingAction.h
  simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc
  simulation/g4simulation/g4tpc/PHG4TpcSubsystem.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1354 Some support materials were added, The overlapping issue was solved, The length of the bus extender was changed
  simulation/g4simulation/g4intt/PHG4InttDefs.h
  simulation/g4simulation/g4intt/PHG4InttDetector.cc
  simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
  simulation/g4simulation/g4intt/PHG4InttDisplayAction.cc
  simulation/g4simulation/g4intt/PHG4InttHitReco.cc
  simulation/g4simulation/g4intt/PHG4InttSubsystem.cc
  simulation/g4simulation/g4intt/configure.ac
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1355 add opening files in pnfs via xrootd
  offline/framework/frog/FROG.cc
  offline/framework/frog/FROG.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-FAIL, CI-build-gcc-8.3-clang-PASS

#1356 Master corrected clusters
  offline/packages/trackbase/TrkrCluster.h
  offline/packages/trackbase/TrkrClusterContainerv3.cc
  offline/packages/trackbase/TrkrClusterv1.cc
  offline/packages/trackbase/TrkrClusterv1.h
  offline/packages/trackbase/TrkrClusterv2.cc
  offline/packages/trackbase/TrkrClusterv2.h
  offline/packages/trackbase/TrkrClusterv3.cc
  offline/packages/trackbase/TrkrClusterv3.h
  offline/packages/trackbase_historic/SvtxTrack_FastSim_v1.cc
  offline/packages/trackbase_historic/SvtxTrack_FastSim_v2.cc
  offline/packages/trackbase_historic/SvtxTrack_v1.cc
  offline/packages/trackbase_historic/SvtxTrack_v2.cc
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.cc
  offline/packages/trackreco/PHMicromegasTpcTrackMatching.h
  offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
  offline/packages/trackreco/PHTpcClusterMover.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-FAIL, CI-build-gcc-8.3-clang-PASS

#1357 Fix truth si association
  offline/packages/trackreco/PHTruthSiliconAssociation.cc
  offline/packages/trackreco/PHTruthSiliconAssociation.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1359 Mbd
  simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
  simulation/g4simulation/g4detectors/PHG4BbcSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4BbcSteppingAction.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1353 updated simulation injection of distortions to cylindrical format etc.
  simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc
  simulation/g4simulation/g4tpc/PHG4TpcDistortion.h
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1358 add first DB tool, just dumping calibration files
  offline/database/dbtools/Makefile.am
  offline/database/dbtools/autogen.sh
  offline/database/dbtools/configure.ac
  offline/database/dbtools/xclient.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1360 Bbc visatt
  simulation/g4simulation/g4detectors/BeamLineMagnetDetector.cc
  simulation/g4simulation/g4detectors/BeamLineMagnetSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
  simulation/g4simulation/g4detectors/PHG4BbcDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4BbcSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4BeamlineMagnetDetector.cc
  simulation/g4simulation/g4detectors/PHG4BlockDetector.cc
  simulation/g4simulation/g4detectors/PHG4CEmcTestBeamDetector.cc
  simulation/g4simulation/g4detectors/PHG4ConeDetector.cc
  simulation/g4simulation/g4detectors/PHG4ConeSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4CylinderDetector.cc
  simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.cc
  simulation/g4simulation/g4detectors/PHG4CylinderGeomv1.h
  simulation/g4simulation/g4detectors/PHG4CylinderGeomv2.cc
  simulation/g4simulation/g4detectors/PHG4CylinderGeomv2.h
  simulation/g4simulation/g4detectors/PHG4CylinderSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4EnvelopeDetector.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1361 Fixing edge cases and improving debug output
  simulation/g4simulation/g4centrality/PHG4CentralityReco.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1362 print out stacktrace for invalid field to see who did this
  offline/packages/PHField/PHField3DCartesian.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1364 TPC Supports and minor central membrane improvement.
  simulation/g4simulation/g4detectors/PHG4SpacalDetector.h
  simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
  simulation/g4simulation/g4tpc/PHG4TpcDetector.h
  simulation/g4simulation/g4tpc/PHG4TpcDisplayAction.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1367 Fix nan
  offline/packages/trackreco/ALICEKF.cc
  offline/packages/trackreco/PHCASeeding.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-FAIL, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-FAIL, CI-build-gcc-8.3-clang-PASS

#1370 Rare Crash Fix
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHActsTrkFitter.h
  offline/packages/trackreco/PHTpcTrackSeedCircleFit.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-FAIL, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1371 Fixing cluster mover surface finding
  offline/packages/tpc/TpcClusterizer.cc
  offline/packages/trackbase/ActsSurfaceMaps.h
  offline/packages/trackbase_historic/ActsTransformations.cc
  offline/packages/trackreco/ActsEvaluator.cc
  offline/packages/trackreco/MakeActsGeometry.cc
  offline/packages/trackreco/MakeActsGeometry.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHTpcClusterMover.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-FAIL, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1372 add lustre dedicated search
  offline/framework/frog/FROG.cc
  offline/framework/frog/FROG.h
Labels: CI-cpp-check-PENDING, CI-build-gcc-8.3-new-PENDING, CI-build-gcc-8.3-scan-PENDING, CI-build-gcc-8.3-clang-PENDING

#1373 fixed channel numbering to match electronics ordering, added Cu from …
  simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
  simulation/g4simulation/g4detectors/PHG4BbcSteppingAction.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-FAIL, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1374 update on Makefile.am and PHG4InttDigitizer.cc in simulation/g4simulation/g4intt
  simulation/g4simulation/g4intt/Makefile.am
  simulation/g4simulation/g4intt/PHG4InttDigitizer.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-FAIL, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1377 Use distortion corrected clusters in pre-propagator circle fitter
  offline/packages/trackreco/PHCASeeding.cc
  offline/packages/trackreco/PHTpcTrackSeedCircleFit.cc
  offline/packages/trackreco/PHTpcTrackSeedCircleFit.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-FAIL, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1376 Remove hard-coded eta limits in HcalRawTowerBuilder
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-FAIL, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1378 Fix to PHSimpleKFProp cluster association with distortions
  offline/packages/trackreco/PHSimpleKFProp.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS

#1379 Hcal decal
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
  simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc
  simulation/g4simulation/g4detectors/PHG4HcalCellReco.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1380 Modify evaluator classes to look for CORRECTED_TRKR_CLUSTER node first.
  simulation/g4simulation/g4eval/DSTEmulator.cc
  simulation/g4simulation/g4eval/SvtxClusterEval.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4eval/SvtxHitEval.cc
  simulation/g4simulation/g4eval/TrackEvaluation.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE
