Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2022-08, with the labels that each got.

#1601 Raw light yield
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
  simulation/g4simulation/g4detectors/PHG4Cell.cc
  simulation/g4simulation/g4detectors/PHG4Cell.h
  simulation/g4simulation/g4detectors/PHG4Cellv1.cc
  simulation/g4simulation/g4detectors/PHG4Cellv1.h
  simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc
  simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainer.cc
  simulation/g4simulation/g4detectors/PHG4ScintillatorSlatContainer.h
  simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.cc
  simulation/g4simulation/g4detectors/PHG4ScintillatorSlatv1.h
  simulation/g4simulation/g4detectors/PHG4SectorDetector.cc
  simulation/g4simulation/g4detectors/PHG4SectorDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4SectorSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4SectorSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4SectorSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4SectorSubsystem.h
  simulation/g4simulation/g4detectors/PHG4SpacalDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4SpacalDisplayAction.h
  simulation/g4simulation/g4detectors/PHG4StepStatusDecode.cc
  simulation/g4simulation/g4detectors/PHG4TrackStatusDecode.cc
  simulation/g4simulation/g4detectors/PHG4ZDCDisplayAction.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1602 save raw light yield in cell only if it exists in the PHG4Hit
  simulation/g4simulation/g4detectors/PHG4HcalCellReco.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1603 Remove tpc g4steps
  simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
  simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h
  simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
  simulation/g4simulation/g4tpc/PHG4TpcDetector.h
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.h
  simulation/g4simulation/g4tpc/PHG4TpcDisplayAction.cc
  simulation/g4simulation/g4tpc/PHG4TpcDistortion.cc
  simulation/g4simulation/g4tpc/PHG4TpcDistortion.h
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.h
  simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc
  simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.h
  simulation/g4simulation/g4tpc/PHG4TpcEndCapDisplayAction.h
  simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlane.h
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadPlaneReadout.h
  simulation/g4simulation/g4tpc/PHG4TpcSteppingAction.cc
  simulation/g4simulation/g4tpc/PHG4TpcSteppingAction.h
  simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1604 added three additional jet properties to enable HF and photon tagging
  simulation/g4simulation/g4jets/Jet.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1605 Update TPOT strip geometry
  simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.cc
  simulation/g4simulation/g4micromegas/PHG4MicromegasHitReco.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1608 set XPload flags to some default if not set to prevent crashes
  offline/framework/ffamodules/XploadInterface.cc
  offline/framework/ffamodules/XploadInterface.h
Labels: CI-cpp-check-AVAILABLE, CI-build-gcc-8.3-new-PENDING, CI-build-gcc-8.3-scan-PENDING, CI-build-gcc-8.3-clang-PENDING

#1598 Add contributing elements to PFlow elements
  offline/packages/particleflow/ParticleFlowElement.h
  offline/packages/particleflow/ParticleFlowElementv1.h
  offline/packages/particleflow/ParticleFlowReco.cc
  offline/packages/particleflow/ParticleFlowReco.h
Labels: CI-cpp-check-FAIL, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1609 move pointer check ahead of dereferencing it
  simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
  simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
  simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1606 Handle MVTX strobe simulation and fix Acts surface bug
  offline/packages/mvtx/Makefile.am
  offline/packages/mvtx/MvtxClusterizer.cc
  offline/packages/mvtx/MvtxHitPruner.cc
  offline/packages/mvtx/MvtxHitPruner.h
  offline/packages/trackreco/PHActsTrkFitter.cc
  offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
  offline/packages/trackreco/PHTruthTrackSeeding.cc
  simulation/g4simulation/g4eval/SvtxEvaluator.cc
  simulation/g4simulation/g4intt/PHG4InttHitReco.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxDigitizer.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.cc
  simulation/g4simulation/g4mvtx/PHG4MvtxHitReco.h
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h
  simulation/g4simulation/g4tpc/PHG4TpcElectronDrift.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.cc
  simulation/g4simulation/g4tpc/PHG4TpcPadBaselineShift.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1610 Fix Crash in ACTS fit due to invalid starting parameters
  offline/packages/trackreco/PHActsTrkFitter.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1611 More cdb
  simulation/g4simulation/g4detectors/Makefile.am
  simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalDetector.h
  simulation/g4simulation/g4detectors/PHG4InnerHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.h
  simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalDetector.h
  simulation/g4simulation/g4detectors/PHG4OuterHcalSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.h
  simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.cc
  simulation/g4simulation/g4detectors/PHG4PSTOFSteppingAction.h
  simulation/g4simulation/g4detectors/PHG4PSTOFSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4PSTOFSubsystem.h
  simulation/g4simulation/g4main/Makefile.am
  simulation/g4simulation/g4main/PHG4Reco.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1615 fix new cppcheck warning
  simulation/g4simulation/g4detectors/BeamLineMagnetSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4BbcSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4InnerHcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4OuterHcalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4PSTOFSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4SectorConstructor.h
  simulation/g4simulation/g4detectors/PHG4SpacalSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4ZDCSubsystem.cc
Labels: CI-cpp-check-FAIL, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1617 Phg4 detector subsystem use cdb
  simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4DetectorSubsystem.h
  simulation/g4simulation/g4detectors/PHG4FullProjTiltedSpacalDetector.cc
  simulation/g4simulation/g4detectors/PHG4GDMLDetector.cc
  simulation/g4simulation/g4detectors/PHG4GDMLDetector.h
  simulation/g4simulation/g4detectors/PHG4GDMLSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4GDMLSubsystem.h
  simulation/g4simulation/g4detectors/PHG4GenHit.cc
  simulation/g4simulation/g4detectors/PHG4GenHit.h
  simulation/g4simulation/g4detectors/PHG4HcalDetector.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1620 Build multiple towers
  offline/packages/NodeDump/DumpCdbUrlSave.cc
  offline/packages/NodeDump/DumpCdbUrlSave.h
  offline/packages/NodeDump/Makefile.am
  offline/packages/NodeDump/PHNodeDump.cc
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
  simulation/g4simulation/g4calo/RawTowerDigitizer.cc
Labels: CI-cpp-check-AVAILABLE, CI-build-gcc-8.3-new-PENDING, CI-build-gcc-8.3-scan-PENDING, CI-build-gcc-8.3-clang-PENDING

#1621 Add single particle, set jets to new jet10, jet30, change default run…
  offline/framework/frog/CreateFileList.pl
Labels: CI-cpp-check-AVAILABLE, CI-build-gcc-8.3-new-PENDING, CI-build-gcc-8.3-scan-PENDING, CI-build-gcc-8.3-clang-PENDING

#1623 Xpload crash
  calibrations/tpc/generator/ChargeMapReader.cc
  offline/framework/ffamodules/XploadInterface.cc
  offline/framework/fun4all/Fun4AllBase.cc
  offline/framework/fun4all/Fun4AllBase.h
  offline/framework/fun4all/Fun4AllDstOutputManager.cc
  offline/framework/fun4all/Fun4AllDstOutputManager.h
  offline/framework/fun4all/Fun4AllDummyInputManager.cc
  offline/framework/fun4all/Fun4AllHistoManager.cc
  offline/framework/fun4all/Fun4AllHistoManager.h
  offline/framework/fun4all/Fun4AllInputManager.h
  offline/framework/fun4all/Fun4AllMonitoring.cc
  offline/framework/fun4all/Fun4AllNoSyncDstInputManager.cc
  offline/framework/fun4all/Fun4AllOutputManager.cc
  offline/framework/fun4all/Fun4AllOutputManager.h
  offline/framework/fun4all/Fun4AllServer.cc
  offline/framework/fun4all/Fun4AllServer.h
  offline/framework/fun4all/Fun4AllSyncManager.cc
  offline/framework/fun4all/Fun4AllUtils.cc
  offline/framework/fun4all/PHTFileServer.cc
  offline/framework/fun4all/TDirectoryHelper.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_Container.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_Container.h
  offline/packages/KFParticle_sPHENIX/KFParticle_DST.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_DST.h
  offline/packages/KFParticle_sPHENIX/KFParticle_MVA.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_MVA.h
  offline/packages/KFParticle_sPHENIX/KFParticle_Tools.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_Tools.h
  offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_eventReconstruction.h
  offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_nTuple.h
  offline/packages/KFParticle_sPHENIX/KFParticle_particleList.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_particleList.h
  offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.h
  offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.cc
  offline/packages/KFParticle_sPHENIX/KFParticle_truthAndDetTools.h
Labels: CI-cpp-check-AVAILABLE, CI-build-gcc-8.3-new-PENDING, CI-build-gcc-8.3-scan-PENDING, CI-build-gcc-8.3-clang-PENDING

#1624 Quick DecayFinder patch
  offline/packages/decayfinder/DecayFinder.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-FAIL, CI-DST-readback-FAIL, CI-build-gcc-8.3-new-PENDING, CI-track-low-occ-QA-PENDING, CI-track-high-occ-QA-PENDING, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-PENDING

#1628 Protect jets
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.h
  simulation/g4simulation/g4calo/RawTowerDigitizer.cc
  simulation/g4simulation/g4jets/ClusterJetInput.cc
  simulation/g4simulation/g4jets/ClusterJetInput.h
  simulation/g4simulation/g4jets/FastJetAlgo.cc
  simulation/g4simulation/g4jets/FastJetAlgo.h
  simulation/g4simulation/g4jets/Jet.h
  simulation/g4simulation/g4jets/JetAlgo.h
  simulation/g4simulation/g4jets/JetHepMCLoader.cc
  simulation/g4simulation/g4jets/JetHepMCLoader.h
  simulation/g4simulation/g4jets/JetInput.h
  simulation/g4simulation/g4jets/JetMap.cc
  simulation/g4simulation/g4jets/JetMap.h
  simulation/g4simulation/g4jets/JetMapv1.cc
  simulation/g4simulation/g4jets/JetMapv1.h
  simulation/g4simulation/g4jets/JetReco.cc
  simulation/g4simulation/g4jets/JetReco.h
  simulation/g4simulation/g4jets/Jetv1.cc
  simulation/g4simulation/g4jets/Jetv1.h
  simulation/g4simulation/g4jets/TowerJetInput.cc
  simulation/g4simulation/g4jets/TrackJetInput.cc
  simulation/g4simulation/g4jets/TrackJetInput.h
  simulation/g4simulation/g4jets/TruthJetInput.cc
  simulation/g4simulation/g4jets/TruthJetInput.h
  simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
  simulation/g4simulation/g4tpc/PHG4TpcEndCapDetector.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1629 Bbc cables
  simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
  simulation/g4simulation/g4detectors/PHG4BbcDisplayAction.cc
  simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.cc
  simulation/g4simulation/g4detectors/PHG4DetectorGroupSubsystem.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1630 Trkrcluster dump
  offline/packages/NodeDump/DumpBbcVertexMap.cc
  offline/packages/NodeDump/DumpCaloTriggerInfo.cc
  offline/packages/NodeDump/DumpEpInfo.cc
  offline/packages/NodeDump/DumpGlobalVertexMap.cc
  offline/packages/NodeDump/DumpJetMap.cc
  offline/packages/NodeDump/DumpObject.cc
  offline/packages/NodeDump/DumpObject.h
  offline/packages/NodeDump/DumpPHG4BlockCellGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4BlockGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4CellContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderCellContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderCellGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4HitContainer.cc
  offline/packages/NodeDump/DumpPHG4InEvent.cc
  offline/packages/NodeDump/DumpPHG4ScintillatorSlatContainer.cc
  offline/packages/NodeDump/DumpPHG4TruthInfoContainer.cc
  offline/packages/NodeDump/DumpPHHepMCGenEventMap.cc
  offline/packages/NodeDump/DumpParticleFlowElementContainer.cc
  offline/packages/NodeDump/DumpPdbParameterMap.cc
  offline/packages/NodeDump/DumpPdbParameterMapContainer.cc
  offline/packages/NodeDump/DumpRawClusterContainer.cc
  offline/packages/NodeDump/DumpRawTowerContainer.cc
  offline/packages/NodeDump/DumpRawTowerGeom.cc
  offline/packages/NodeDump/DumpRawTowerGeom.h
  offline/packages/NodeDump/DumpRawTowerGeomContainer.cc
  offline/packages/NodeDump/DumpSvtxTrackMap.cc
  offline/packages/NodeDump/DumpSvtxVertexMap.cc
  offline/packages/NodeDump/DumpSyncObject.cc
  offline/packages/NodeDump/DumpTowerBackground.cc
  offline/packages/NodeDump/DumpTrkrClusterContainer.cc
  offline/packages/NodeDump/DumpTrkrClusterHitAssoc.cc
  offline/packages/NodeDump/DumpTrkrHitSetContainer.cc
  offline/packages/NodeDump/DumpTrkrHitTruthAssoc.cc
  offline/packages/NodeDump/DumpVariableArray.cc
  offline/packages/NodeDump/DumpVariableArrayInt.cc
  offline/packages/NodeDump/PHNodeDump.cc
  offline/packages/NodeDump/PHNodeDump.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1631 Dump fixes
  offline/packages/NodeDump/DumpTrkrClusterContainer.cc
  offline/packages/trackbase/TrkrClusterContainerv3.cc
  offline/packages/trackbase/TrkrClusterContainerv4.cc
  offline/packages/trigger/CaloTriggerInfov1.cc
  offline/packages/trigger/CaloTriggerInfov1.h
  offline/packages/trigger/CaloTriggerSim.cc
  offline/packages/trigger/CaloTriggerSim.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1632 start with clang-tidy
  .clang-tidy
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1633 Check surfaces
  offline/packages/trackreco/MakeActsGeometry.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1634 Clang tidy test
  offline/framework/fun4all/Fun4AllInputManager.cc
  offline/framework/fun4all/Fun4AllMonitoring.cc
  offline/framework/fun4all/Fun4AllOutputManager.cc
  offline/framework/fun4all/Fun4AllServer.cc
  offline/packages/NodeDump/DumpBbcVertexMap.cc
  offline/packages/NodeDump/DumpCaloTriggerInfo.cc
  offline/packages/NodeDump/DumpCdbUrlSave.cc
  offline/packages/NodeDump/DumpCentralityInfo.cc
  offline/packages/NodeDump/DumpCentralityInfo.h
  offline/packages/NodeDump/DumpEpInfo.cc
  offline/packages/NodeDump/DumpEventHeader.cc
  offline/packages/NodeDump/DumpEventHeader.h
  offline/packages/NodeDump/DumpFlagSave.cc
  offline/packages/NodeDump/DumpGlobalVertexMap.cc
  offline/packages/NodeDump/DumpInttDeadMap.cc
  offline/packages/NodeDump/DumpJetMap.cc
  offline/packages/NodeDump/DumpPHFieldConfig.cc
  offline/packages/NodeDump/DumpPHFieldConfig.h
  offline/packages/NodeDump/DumpPHG4BlockCellGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4BlockGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4CellContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderCellContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderCellGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4CylinderGeomContainer.cc
  offline/packages/NodeDump/DumpPHG4HitContainer.cc
  offline/packages/NodeDump/DumpPHG4InEvent.cc
  offline/packages/NodeDump/DumpPHG4ParticleSvtxMap.cc
  offline/packages/NodeDump/DumpPHG4ScintillatorSlatContainer.cc
  offline/packages/NodeDump/DumpPHG4TruthInfoContainer.cc
  offline/packages/NodeDump/DumpPHHepMCGenEventMap.cc
  offline/packages/NodeDump/DumpParticleFlowElementContainer.cc
  offline/packages/NodeDump/DumpPdbParameterMap.cc
  offline/packages/NodeDump/DumpPdbParameterMapContainer.cc
  offline/packages/NodeDump/DumpRawClusterContainer.cc
  offline/packages/NodeDump/DumpRawTowerContainer.cc
  offline/packages/NodeDump/DumpRawTowerGeomContainer.cc
  offline/packages/NodeDump/DumpRunHeader.cc
  offline/packages/NodeDump/DumpRunHeader.h
  offline/packages/NodeDump/DumpSvtxPHG4ParticleMap.cc
  offline/packages/NodeDump/DumpSvtxTrackMap.cc
  offline/packages/NodeDump/DumpSvtxVertexMap.cc
  offline/packages/NodeDump/DumpSyncObject.cc
  offline/packages/NodeDump/DumpTowerBackground.cc
  offline/packages/NodeDump/DumpTpcSeedTrackMap.cc
  offline/packages/NodeDump/DumpTrackSeedContainer.cc
  offline/packages/NodeDump/DumpTrkrClusterContainer.cc
  offline/packages/NodeDump/DumpTrkrClusterCrossingAssoc.cc
  offline/packages/NodeDump/DumpTrkrClusterHitAssoc.cc
  offline/packages/NodeDump/DumpTrkrHitSetContainer.cc
  offline/packages/NodeDump/DumpTrkrHitTruthAssoc.cc
  offline/packages/NodeDump/DumpTrkrHitTruthClusters.cc
  offline/packages/NodeDump/DumpVariableArray.cc
  offline/packages/NodeDump/DumpVariableArrayInt.cc
  offline/packages/NodeDump/PHNodeDump.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1635 Light maps gdml
  simulation/g4simulation/g4ihcal/PHG4IHCalSteppingAction.cc
  simulation/g4simulation/g4ohcal/PHG4OHCalSteppingAction.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1616 Add code to generate a vector to access the JetMap data.
  simulation/g4simulation/g4jets/Jet.h
  simulation/g4simulation/g4jets/JetMap.h
  simulation/g4simulation/g4jets/JetMapv1.cc
  simulation/g4simulation/g4jets/JetMapv1.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1627 modified the TPC hanger materials to reflect updated design
  simulation/g4simulation/g4tpc/PHG4TpcDetector.cc
  simulation/g4simulation/g4tpc/PHG4TpcEndCapSubsystem.cc
  simulation/g4simulation/g4tpc/PHG4TpcSubsystem.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE

#1640 Add embed setter for QA modules
  offline/QA/modules/QAG4SimulationTracking.cc
  offline/QA/modules/QAG4SimulationTracking.h
  offline/QA/modules/QAG4SimulationVertex.cc
  offline/QA/modules/QAG4SimulationVertex.h
  offline/packages/trackreco/MakeActsGeometry.h
  offline/packages/trackreco/PHSiliconTpcTrackMatching.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-FAIL, CI-calo-QA-PENDING, CI-DST-readback-PASS, CI-build-gcc-8.3-new-FAIL, CI-track-low-occ-QA-AVAILABLE, CI-track-high-occ-QA-AVAILABLE, CI-build-gcc-8.3-scan-PASS, CI-build-gcc-8.3-clang-PASS, CI-track-pythia-QA-AVAILABLE
