Repository sPHENIX-Collaboration/coresoftware, pull requests merged in 2023-02, with the labels that each got.

#1816 correction to spacecharge summing
  calibrations/tpc/generator/ChargeMapReader.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1817 quit if the name of a funall object is an empty string
  offline/framework/fun4all/Fun4AllBase.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1818 Update PHG4EPDDetector.cc
  simulation/g4simulation/g4epd/PHG4EPDDetector.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1820 Added event number tracking and modulo to CM hit generation
  simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.cc
  simulation/g4simulation/g4tpc/PHG4TpcCentralMembrane.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1821 Updates to Jet Tagging macros - new features, bug fixes
  offline/packages/KFParticle_sPHENIX/KFParticle_sPHENIX.cc
  offline/packages/ResonanceJetTagging/ResonanceJetTagging.cc
  offline/packages/ResonanceJetTagging/ResonanceJetTagging.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-PENDING, CI-track-pythia-QA-PENDING, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1825 Tpot geometry
  simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc
  simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1826 Adding epd hit reco
  simulation/g4simulation/g4epd/Makefile.am
  simulation/g4simulation/g4epd/PHG4EPDDetector.cc
  simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc
  simulation/g4simulation/g4epd/PHG4EPDModuleReco.h
  simulation/g4simulation/g4epd/PHG4EPDSteppingAction.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1827 added three utility macros/scripts which are used to generate time or…
  calibrations/tpc/generator/clone_job_with_new_file.sh
  calibrations/tpc/generator/multiSubmit.sh
  calibrations/tpc/generator/writeTimeOrderedDistortions.C
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1828 Added MBD/BBC Supports
  simulation/g4simulation/g4detectors/PHG4BbcDetector.cc
  simulation/g4simulation/g4detectors/PHG4BbcDetector.h
  simulation/g4simulation/g4detectors/PHG4BbcDisplayAction.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-FAIL, CI-build-gcc-12.1.0-clang-FAIL, CI-build-gcc-12.1.0-scan-PASS

#1829 tpot_geometry_2
  simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc
Labels: CI-cpp-check-AVAILABLE, CI-build-gcc-12.1.0-new-FAIL, CI-build-gcc-12.1.0-clang-FAIL, CI-build-gcc-12.1.0-scan-FAIL

#1822 updated the complete jet reconstruction to enable use of TowerInfo objects
  offline/packages/CaloBase/TowerInfov1.h
  offline/packages/jetbackground/CopyAndSubtractJets.cc
  offline/packages/jetbackground/CopyAndSubtractJets.h
  offline/packages/jetbackground/DetermineTowerBackground.cc
  offline/packages/jetbackground/DetermineTowerBackground.h
  offline/packages/jetbackground/RetowerCEMC.cc
  offline/packages/jetbackground/RetowerCEMC.h
  offline/packages/jetbackground/SubtractTowers.cc
  offline/packages/jetbackground/SubtractTowers.h
  simulation/g4simulation/g4calo/RawTowerDigitizer.cc
  simulation/g4simulation/g4jets/Jet.h
  simulation/g4simulation/g4jets/TowerJetInput.cc
  simulation/g4simulation/g4jets/TowerJetInput.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-FAIL, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1830 Fix trigger for loop type
  offline/packages/trigger/CaloTriggerSim.cc
  offline/packages/trigger/CaloTriggerSim.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1831 Secondary vertex finder
  offline/packages/trackreco/Makefile.am
  offline/packages/trackreco/PHSimpleVertexFinder.cc
  offline/packages/trackreco/PHSimpleVertexFinder.h
  offline/packages/trackreco/SecondaryVertexFinder.cc
  offline/packages/trackreco/SecondaryVertexFinder.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1832 Tpot geometry 3
  offline/packages/micromegas/CylinderGeomMicromegas.cc
  offline/packages/trackreco/MakeActsGeometry.cc
  simulation/g4simulation/g4micromegas/Makefile.am
  simulation/g4simulation/g4micromegas/PHG4MicromegasDetector.cc
  simulation/g4simulation/g4micromegas/PHG4MicromegasSurvey.cc
  simulation/g4simulation/g4micromegas/PHG4MicromegasSurvey.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-FAIL, CI-build-gcc-12.1.0-new-FAIL, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1835 Fix epd
  offline/packages/NodeDump/DumpTowerInfoContainer.cc
  offline/packages/NodeDump/DumpTowerInfoContainer.h
  offline/packages/NodeDump/Makefile.am
  offline/packages/NodeDump/PHNodeDump.cc
  simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc
  simulation/g4simulation/g4epd/PHG4EPDModuleReco.h
Labels: CI-cpp-check-AVAILABLE, CI-build-gcc-12.1.0-new-PENDING, CI-build-gcc-12.1.0-clang-PENDING, CI-build-gcc-12.1.0-scan-PENDING

#1834 Fixed phi and z bin number and added sampa_tbias
  simulation/g4simulation/g4tpc/TpcClusterBuilder.cc
  simulation/g4simulation/g4tpc/TpcClusterBuilder.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1836 Fix epd
  simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc
Labels: CI-cpp-check-PENDING, CI-build-gcc-12.1.0-new-PENDING, CI-build-gcc-12.1.0-clang-PENDING, CI-build-gcc-12.1.0-scan-PENDING

#1837 fall back to pythia6 decayer
  simulation/g4simulation/g4main/PHG4Reco.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1839 Fix towerinfo
  offline/packages/CaloBase/TowerInfoContainer.cc
  offline/packages/CaloBase/TowerInfoContainer.h
  offline/packages/CaloBase/TowerInfoContainerv1.h
  offline/packages/NodeDump/DumpTowerInfoContainer.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1840 Add flag to skip noise addition for empty time bins
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.cc
  simulation/g4simulation/g4tpc/PHG4TpcDigitizer.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1841 Add functionality for counting number of GEM modules hit + clearing up ambiguity w/ arbitrary pointing
  offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
  offline/packages/tpccalib/TpcDirectLaserReconstruction.h
  simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1838 Recover `std::cout` to previous behavior after EvtGen load
  simulation/g4simulation/g4decayer/EvtGenExtDecayerPhysics.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1844 Fixing issue with pointing of lasers in TPC
  simulation/g4simulation/g4tpc/PHG4TpcDirectLaser.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1843 updated the interface to towerinfocontainer to remove the use of maps
  offline/packages/CaloBase/Makefile.am
  offline/packages/CaloBase/TowerInfoContainer.cc
  offline/packages/CaloBase/TowerInfoContainer.h
  offline/packages/CaloBase/TowerInfoContainerv1.cc
  offline/packages/CaloBase/TowerInfoContainerv1.h
  offline/packages/CaloReco/CaloTowerBuilder.cc
  offline/packages/CaloReco/CaloTowerBuilder.h
  offline/packages/CaloReco/CaloTowerCalib.cc
  offline/packages/CaloReco/RawTowerCalibration.cc
  offline/packages/NodeDump/DumpTowerInfoContainer.cc
  offline/packages/jetbackground/CopyAndSubtractJets.cc
  offline/packages/jetbackground/DetermineTowerBackground.cc
  offline/packages/jetbackground/RetowerCEMC.cc
  offline/packages/jetbackground/SubtractTowers.cc
  simulation/g4simulation/g4calo/HcalRawTowerBuilder.cc
  simulation/g4simulation/g4calo/RawTowerBuilder.cc
  simulation/g4simulation/g4calo/RawTowerDigitizer.cc
  simulation/g4simulation/g4epd/PHG4EPDModuleReco.cc
  simulation/g4simulation/g4jets/TowerJetInput.cc
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PENDING, CI-build-gcc-12.1.0-clang-PENDING, CI-build-gcc-12.1.0-scan-PENDING

#1845 Moving GEM counting functionality to associated hits instead of clusters + adding histograms
  offline/packages/tpccalib/TpcDirectLaserReconstruction.cc
  offline/packages/tpccalib/TpcDirectLaserReconstruction.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1846 make EvtGen default decayer
  simulation/g4simulation/g4main/PHG4Reco.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1833 Include User Interface to Allow Loading User Customized Decay File (e.g. forced decay)
  offline/QA/modules/QAG4Decayer.cc
  simulation/g4simulation/g4decayer/EvtGenExtDecayerPhysics.cc
  simulation/g4simulation/g4decayer/EvtGenExtDecayerPhysics.hh
  simulation/g4simulation/g4decayer/G4EvtGenDecayer.cc
  simulation/g4simulation/g4main/PHG4Reco.cc
  simulation/g4simulation/g4main/PHG4Reco.h
Labels: preview-do-not-merge, CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS

#1847 Rawtodst
  offline/packages/rawtodst/Makefile.am
  offline/packages/rawtodst/TPCMap.cc
  offline/packages/rawtodst/TPCMap.h
  offline/packages/rawtodst/TPC_RawHit.h
  offline/packages/rawtodst/autogen.sh
  offline/packages/rawtodst/configure.ac
  offline/packages/rawtodst/tpc_hits.cc
  offline/packages/rawtodst/tpc_hits.h
Labels: CI-cpp-check-AVAILABLE, CI-valgrind-AVAILABLE, CI-calo-QA-AVAILABLE, CI-DST-readback-PASS, CI-track-low-occ-QA-AVAILABLE, CI-track-pythia-QA-AVAILABLE, CI-build-gcc-12.1.0-new-PASS, CI-build-gcc-12.1.0-clang-PASS, CI-build-gcc-12.1.0-scan-PASS
